.\" -*- nroff -*-
.\" Copyright (c) 2001-2005 Central North Publishing Limited.
.\" All rights reserved.
.\"
.\".hla de
.TH WXTOIMG UPGRADE  "version 2.7.2"
.SH Upgrade
.B Wie funktioniert das Upgrade (Aufrüstung auf erweiterte Version)?
.br
Rufen Sie in Ihrem Browser folgende Adresse auf:
.nf
    http://www.wxtoimg.com/reg/
.fi
.PP
und folgen Sie den Anweisungen. Für eine geringe Gebühr erhalten Sie
einen persönlichen Upgrade-Schlüssel zugesandt, mit dem Sie die zusätzlichen
Funktionen freischalten können.
.PP
.B Warum soll ich aufrüsten?
.br
Hierdurch wird die fortlaufende Weiterentwicklung ermöglicht. Ausserdem
erhalten Sie Zugriff auf weitere Funktionen.
.PP
Es liegen zwei Upgrade-Versionen vor. Die Standard- und Professional-
Version.
.PP
.B Welche zusätzlichen Funktionen erhalte ich bei Kauf der Standard-Version?
.br
Anaglyph-3D-Konvertierungen.  Diese bieten einen überwältigenden Blick
auf die einzelnen Wolkenschichten.  Zur Betrachtung werden spezielle
rot/blau-Brillen benötigt.
.PP
Fügt eine Konvertierungart mit (geschätzten) Niederschlägen hinzu.
.PP
Diese Konvertierungsart funktioniert allerdings nicht bei schmalbandigen
Empfängern. Bei den anderen Konvertierungsarten ergibt sich eine
bedeutend verbesserte Bildqualität für schmalbandige Empfänger (z. B.
Scanner, Radios).
.PP
Web-Seiten können individuell gestaltet werden.
.PP
Stellt viele weitere Projektionen bereit (Kartendarstellungen)
unter anderem die Merkator Projektion mit zusätzlichen Optionen
(wie die zentraler- oder Referenzlängengrad, Massstab und Grenzen)
zur Einstellung der Umsetzung der APT-Satellitenbilder.
.PP
Es können aus Bildern verschiedener Umläufe Filme erstellt
werden (Wolkenbewegung über fixer Landdarstellung).
.PP
Aus mehreren Umläufen können Bilder zu einem grossen Gesamtbild
zusammengesetzt werden.
.PP
Stellt Bildbearbeitungsmöglichkeiten bereit, wie Drehen, 
Farbanpassung und Konvertierung zu Graustufen.
.PP
Zur automatischen Einstellung von Länge und Breite kann das GPS
(NMEA) benutzt werden.
.PP
Die lokale Zeit (anstatt UTC) kann angezeigt werden.
.PP
Die Länge und Breite unter dem Cursor in APT-Bildern
wird zusammen mit der Entfernung (und Richtung) zum 
eigenen Standort angezeigt.
.PP
Bei der Anzeige von Informationen in Bildern kann die 
Schriftgrösse und Farbe ausgewählt werden. Dies kann 
automatisch in Abhängigkeit von Satellit und Bild für
den Namen des Satelliten, Zeit und Ort des Überflugs und
viele weitere Details erfolgen.
.PP
Menüs können so eingestellt werden, dass sie ständig am
Bildschirm sichtbar bleiben. Das vereinfacht die Auswahl
von Konvertierungen und anderen Optionen.
 Diese Option ist für MacOS X nicht verfügbar.
.PP
Bedienung aus dem Programm heraus für folgende Geräte: FT-847, 
PCR100/PCR1000, R2FX, SAN 200, WRX-137, Timestep Proscan 
i-interface, AOR, Uniden Bearcat,
ICOM und Kenwood-Empfänger und Unterstützung von Ihren eigenen
Bedienprogrammen.
.PP
Die Konfiguration ist in der Art möglich, dass automatisch
bei einem Überflug die Aufnahme und Dekodierung gestartet werden.
.PP
Die zukünftige Entwicklung orientiert sich ausschliesslich
auf Funktionen für Käufer der Standard-Version.
.PP
Weder die Standard- noch die Freeware-Version dürfen kommerziell genutzt
werden.
.PP
.B Welche weiteren Funktionen erhalte ich bei Kauf der Professional-Version?
.br
Die Professional-Version unterstützt alle Funktionen
der Standard-Version und zusätzlich:
.PP
eine Auswahl von Algorithmen für die geographische Darstellung,
.PP
weitere Rausch-Filter-Optionen,
.PP
weitere Kontrast-Optionen,
.PP
erweiterte Einstellmöglichkeiten der Sensoren für die HVCT- und HVC-
Konvertierungen
.PP
und darf kommerziell eingesetzt werden.
.PP
.B Vielen Dank
.br
im voraus, dass Sie hier upgraden:
.nf
    http://www.wxtoimg.com/reg/
.fi
.PP
.SH Copyright
Copyright (c) 2001-2005 Central North Publishing Limited.  All rights reserved.
