.\" -*- nroff -*-
.\" Traducción al español de Paulí Núñez, EA3BLQ 
.\" Copyright (c) 2001-2004 Central North Publishing Limited.
.\" All rights reserved.
.\"
.\".hla es
.TH WXTOIMG Registro "Versión 2.7.2"
.SH Registro (Upgrade)
.B ¿Como puedo registrarme?
.br
Utilice su explorador de Internet para entrar en el portal
.nf
    http://www.wxtoimg.com/reg/
.fi
.br
y siga las instrucciones. Por una módica aportación recibirá un código personal de registro (upgrade) que le permitirá abrir completamente el programa y disfrutar de prestaciones adicionales.
.PP
.B ¿Por qué debería registrarme?
.br
El registrarse hace posible una continuidad en el desarrollo del programa. En este caso además el programa abrirá el uso de prestaciones adicionales, vedadas a quien no se registra.
.PP
Existen dos versiones registradas, la Estándar y la Profesional 
.PP
.B ¿De qué prestaciones adicionales puedo disponer si me registro a la versión Estándar?
.br
La mejora o embellecimiento Anaglyph 3-D, que puede proporcionar una impresionante y espectacular forma de visualizar las  capas de nubes. Se precisan gafas 3-D con cristales rojo y azul.
.PP
Enriquecimientos adicionales con superposiciones de precipitaciones (estimadas).
.PP
Mejora excepcional en la calidad de las imágenes procedentes de receptores con un ancho de banda estrecho (e.g. escáner y receptores de comunicación).
.PP 
Al registrarse, las páginas WEB pueden ser enteramente personalizadas.
.PP
Acceso a muchos otros modos de proyección (transformaciones geográficas) incluyendo la proyección Mercator junto con otras opciones (tales como longitud central o de referencia, escala y confines geográficos) para controlar la transformación de imágenes APT procedentes de satélites orbitales.
.PP
Permite crear películas animadas de las imágenes procedentes de múltiples satélites polares (nubes en movimiento, tierra inmóvil).
.PP
Crear composición de imágenes procedentes de múltiples pases de satélite para cubrir un área más grande.
.PP
Permite la rotación de imágenes así como el cambio de color y la conversión a escala de grises.
.PP
También permite el uso de un dispositivo GPS (NMEA) para establecer automáticamente la longitud y latitud de la estación receptora.
.PP
Permite que se muestre la hora local en lugar de la hora UTC.
.PP
En las imágenes APT, se muestra la latitud y longitud correspondiente al punto señalado por el puntero del ratón en la imagen, así como la dirección y distancia en Km. que media desde ese punto señalado hasta la ubicación de la estación terrestre.
.PP
Opcionalmente se puede incluir información escrita sobre la imagen, pudiendo seleccionar el tamaño de la fuente y el color. Esta opción puede automatizarse para que incluya el nombre del satélite, fecha, hora y localización del pase junto con otros detalles relativos al satélite o la imagen.
.PP
Dispone de menús emergentes que pueden permanecer siempre visibles para una mayor facilidad de selección de las mejoras o enriquecimientos (Enhancements) o de las Opciones. Esta opción no está disponible para MacOS X.
.PP
Da soporte para el control de los receptores FT-847, PCR100/PCR1000, R2FX, SAN 200, WRX-137, AOR, Uniden Bearcat, ICOM y Kenwood, así como para los programas CAT de control remoto, suministrados por el propio usuario.
.PP
Permite la configuración del programa para que ejecute automáticamente la modalidad record/decode en el momento de cargar el programa, consiguiendo así una decodificación completamente automática.
.PP
Lo que es más, todo el trabajo de desarrollo de la versión Estándar que se haga en el futuro, estará enfocado a la consecución de nuevas prestaciones para los usuarios registrados.
.PP
El uso de las versiones "freeware" (gratuita) o Estándar (registrada) queda prohibido para fines comerciales.
.PP
.B Si adquiero el registro para la versión Profesional ¿qué prestaciones adicionales consigo?
.br
La versión Profesional dispone de todas las prestaciones de la versión Estándar, más:
.PP
El registro permite el uso de una variedad de algoritmos de remuestreo (para transformaciones geográficas)
.PP
Dispondrá de más opciones de filtro de ruido,
.PP
Opciones de contraste adicionales, y
.PP
Podrá usar el programa para fines comerciales.
.PP
.B Agradecimiento
.br
Gracias anticipadas por su registro en:
.nf
    http://www.wxtoimg.com/reg/
.fi
.PP
.SH Copyright
Traducción al español de Paulí Núñez, EA3BLQ 
.PP
Copyright (c) 2001-2004 Central North Publishing Limited.  Reservados todos los derechos.
