.\" -*- nroff -*-
.\"
.\" Copyright (c) 2001-2004 Central North Publishing Limited.
.\" All rights reserved.
.\"
.\".hla fr
.TH WXTOIMG Mise à niveau "Versión 2.7.3"
.SH Mise à niveau
\fBComment je mets à niveau?\fP
.br
Dirigez votre navigateur à:
.nf
    http://www.wxtoimg.com/reg/
.fi
.br
et suivez les instructions. Pour une somme modique vous sera envoyé une clef personnelle de mise à niveau que vous pouvez utiliser pour permettre des particularités complémentaires.
.PP
.B Pourquoi dois-je mettre à niveau?
.br
La modernisation rend possible le développement continu de l'aide. En plus, en mettant à niveau des particularités complémentaires deviennent disponibles.
.PP
Il y a deux éditions de mise à niveau, l'Édition Standard et l'Édition Professionnelle.
.PP
.B Quelles particularités complémentaires sont permissent quand j'achète l'Édition Standard?
.br
Améliorations anaglyphes 3-D. Celles-ci peuvent fournir une manière stupéfiante de voir les couches de nuages. Elles doivent être regardées avec des lunettes spéciales rouges/bleus.
.PP
Ajoute des améliorations avec des recouvrements de précipitation (estimés).
.PP
Qualité d'image très améliorée pour récepteurs à bande étroite (par exemple scanners, récepteurs de communication).
.PP
Les pages web peuvent être complètement personnalisées quand vous mettez à niveau.
.PP
Permet beaucoup d'autres projections ( transformations géographiques) incluant la projection Mercator avec permission d'options (comme le centre ou longitude de référence, échelle et frontières) pour contrôler la transformation des images de satellites APT.
.PP
Tient compte de la création de films animés d'images multiples de satellites polaires (nuage se déplaçant, terre stationnaire).
.PP
Des images composées peuvent être créées des passages de satellites polaires afin de couvrir un plus grand secteur.
.PP
Permet des possibilités de rotation d'image avec changement de couleur et conversion d'échelle de gris.
.PP
Permet à un GPS (NMEA) d'être utilisé pour automatiquement mettre la latitude et la longitude.
.PP
Permet à l'heure locale (au lieu du temps UTC) d'être montrée.
.PP
La latitude et la longitude sous le curseur sont montrées avec la distance (et direction) de la station au sol dans les images APT.
.PP
L'information peut être facultativement montrée sur les images dans une police de taille et couleur sélectionnable. Ceci peut être automatisé et peut inclure le nom du satellite, le temps l'emplacement du passage avec beaucoup d'autres détails liés au satellite et à l'image.
.PP
L'arrachement des menus est soutenu. Ceci permet un choix plus facile des améliorations et des options par les fenêtres qui sont toujours à l'écran. Cette option n'est pas disponible sur MacOS X.
.PP
Fournit l'appui pour contrôler les récepteurs FT-847, PCR100/PCR1000, R2FX, SAN 200, WRX-137, AOR, Uniden Bearcat, ICOM, et Kenwood et l'appui pour un programme de radiocommande fourni par l'utilisateur.
.PP
Permet au programme d'être configuré pour entrer automatiquement  en mode enregistrement/décodage au début d'un passage satellite pour enregistrement complètement automatisé.
.PP
En outre, le travail futur se concentrera sur des particularités seulement pour les utilisateurs qui ont acheté l'
édition standard.
.PP
Ni l'édition standard ni l'édition du logiciel public ne peuvent être employés à des fins commerciales.
.PP
.B Quelles particularités complémentaires sont permissent quand j'achète l'Édition Professionnelle?
.br
L'Édition Professionnelle fournit toutes les particularités de l'Édition Standard, plus:
.PP
fournit un choix d'algorithmes re-échantillonné (pour la transformation géographique),
.PP
fournit des options de filtre anti-bruit complémentaire,
.PP
fournit des options complémentaires de contraste et peut être employé à des fins commerciales.
.PP
.B Merci
.br
d'avance pour votre mise à niveau à: 
.nf
    http://www.wxtoimg.com/reg/
.fi 
.PP
.SH Droit d'auteur
Droit d'auteur (c) 2001-2004 Central North Publishing Limited. Tous droits réservés.
