.\" -*- nroff -*-
.\" Copyright (c) 2001-2004 Central North Publishing Limited.
.\" All rights reserved.
.\" Translated by Nakato Mikiya
.\"
.TH Required Calibration "2.7.3"
.SH 調整をしましょう
より良い画像に必要なのは、受信場所の緯度と経度、最新の衛星軌道要素です。それと、録音の音量調整も必要です。
.br
また、貴方がお使いのサウンドカードのサンプル割合とサンプリング周波数を一致させましょう。貴方は、一度だけこの周波数修正を行う必要があります。
.TP 10
訳者端書き: 実際のサンプリング割合
WXtoImgのサンプリング割合は、11025Hzです。しかし、貴方がお使いのサウンドカードがごくわずかに早かったり、または遅いサンプリング割合になっています(例えば、11025.26Hzならば、わずか0.0026%だけ速いことになります)。そこで、サウンドカードの水晶発振子の速度をWXtoImgに正確に教えましょう。「斜めな画像の修正(サンプリング周波数の調節)」に詳しくあります。
.PP
.B WXtoImgを使い始める前に...
.br
サウンドカードのライン入力と、受信機のオーディオ出力を接続して下さい。ICOM製PCR1000を使うならば、ライン・レベル出力にするジャンパー設定にして下さい。
.PP
極軌道衛星の送信周波数は、137.30、137.40、137.50、137.62、137.80、137.85MHzです。ただし、送信を停止している衛星もあります。
.br
各衛星は12時間間隔で毎日二度、同じ時間帯に通過しています。また、衛星が貴方の真上を通過する1時間半から2時間前後には、低い高度で通過します。好条件の通過は、およそ15分間続きます。
.br
\fIWXtoImg\fPは受信待機の状態で、通過する衛星名と飛行方向と最高角度や周波数を表示します。
.PP
.B 貴方の緯度と経度
.br
[Options]にある[Ground Station Location...]
を見て下さい。[City:]には貴方が受信する都市名をアルファベットで、[Country:]には日本ならば"japan"と入れて下さい。都市人口が10万人以上ならば
[Lookup Lat/Lon]
を押すと、緯度と経度が表示されるでしょう。
.PP
[Lookup Lat/Lon]
を押しても都市の緯度と経度が表示されないならば、その数字を入れましょう。緯度と経度は度単位です。緯度は、例えば35.500です。(52:30, 52:30:00, 52:30.00などではありません)北緯と東経は正の数字を、南緯と西経は負の数字を使います。
.PP
受信する場所の緯度と経度が分からないならば、最も近くの人口10万人以上の都市名を入れて
[Lookup Lat/Lon]
を押しましょう。標高が分からないならば、[Altitude]には"0.0"を入れて下さい。
.PP
.B 軌道要素を最新にしましょう
.br
コンピュータをインターネットへ接続してから、[File]にある
[Update Keplers]
を押して下さい。これは、気象衛星の最新軌道要素を取り入れます。もし貴方がインターネットに接続をしないならば、
[Update Keplers]
を行わず、また、地表図を表示しないように、[Options]にある
[Disable Map Overlay]
を選んで下さい。
.PP
.B 衛星が通過する時刻を見ましょう
.br
[File]にある
[Satellite Pass List]
を見て下さい。これは、現在の時刻から一週間後までに、貴方の付近を通過する衛星を表示します。時刻は、現地時間と世界標準時の両方を表示します。
.PP
.B 音量を調節しましょう
.br
受信機の音量をやや低くし、[File]にある
[Mixer Control...]
を押してミキサーを見て下さい。受信機からの音量(たいていはライン・イン)を調節しましょう。
.PP
受信機からのPCM(録音レベル)を最大にしましょう。また、ラインレベル(LinuxとMS-Windows)を中間ぐらいにします。Linuxではigain(録音レベル)を中間ぐらいにします。
.br
初めての録音では、受信機の音量とライン入力は低めにしましょう。
.PP
.TP 10
訳者端書き: XMixerとigain
XMixerでは、カセットテープのアイコンや"igain"が録音レベルになります。先ずはこれらを上げましょう。サウンドドライバモジュールが読み込まれると、ミキサーの設定が初期状態になることがあります。その場合は、例えば次の行を/etc/modules.confに追加するとサウンドドライバが読み込まれた直後にミキサープログラム(下例ではsetmixer)が動き、指定した録音レベルになります。
.PP
options sound dma_buffsize=65536 && /usr/bin/setmixer igain 0 ogain 0 vol 75
.PP
.PP
MS-Windows95などでは、ミキサー・コントロールにあるオプションメニューからプロパティを表示し、録音元を選ぶ必要があるでしょう。また、音量調節をする前にライン入力を選びましょう。
.PP
[File]にある[Record...]を選び、[Record]を押します。
.PP
そのまま、衛星が飛来するのを待って下さい。WXtoImg画面の下側には飛来する予定の衛星名と送信周波数と通過時刻(世界標準時)が表示されます。
.PP
WXtoImgは衛星通過時に録音をし、同時に画像を表示します。未解析の画像には、大きな明暗差があるかもしれません。また、もしかすると未解析の画像は斜めになっているかもしれませんが、後の解析には影響がありません。
.PP
表示される未解析画像を、音量調整の目安に使わないで下さい。音量調整については、別記を参照して下さい。録音が完全ならば、WXtoImgは地表図を作り、画像を再解析します。再解析では最良な画像を作ります。
.PP
録音中はスクロールバーが使えないかもしれません。また、画像をスクロールすると画像が切れて見えるかもしれません。
.PP
受信の録音が始まると、WXtoImg画面に音量が表示されます。衛星が通過中にもかかわらず、WXtoImg画面が信号を待つ表示ならば、受信機の音量又はミキサー入力が低すぎます。録音中の表示になるように、受信機かミキサーの録音音量のどちらか、又は両方の音量をゆっくりと上げましょう。
.br
衛星通過中にWXtoImg画面の音量が50.0から75.0の範囲になるように、受信機やミキサーの録音音量を簡単に調節ができるでしょう。
.PP
もし、受信機の音量調整ができないならば、表示される音量が50.0から75.0の範囲になるように、コンピュータのミキサー(録音やigain、あるいは入力ラインレベル)を調節して下さい。
.PP
受信記録中の音量表示は、緑色です。赤色や黄色は音量の高すぎや低すぎを示します。
.PP
衛星が通過した後に、再解析された画像が表示されます。解析が終わると、音量がWXtoImg画面右下に表示されます。
.PP
繰り返しますが、音量表示が50.0から75.0の間になるよう音量を調整しましょう。高い数字(例えば90.2)ならば音量を下げ、低い数字(例えば24.7)ならば音量を上げましょう。音量が高すぎると画像の細かい部分が消え、白く表示されます。音量が低くすぎると、画像全体の細かい表示がされません。
.PP
音量調節をする時以外は、衛星の通過中に音量を変えることは、避けて下さい。通過時に音量を変えると、再解析した画像に帯状に濃度のむらができ、温度測定に悪影響があります。
.PP
綺麗な画像の為に、音量調節を繰り返しましょう。
.PP
.B 斜めな画像の修正(サンプリング周波数の調節)
.br
ここではPLLを不使用にし、サンプリング割合をより正確に指定します。先ずは。
.PP
次に、[File]にある
[Open Audio File...]
から解析する録音記録を選んで下さい。頭上を通過したNOAA衛星の録音を使うのが良いでしょう(A,Bの2チャンネルの画像が表示されます)。
.PP
解析された画像が表示されるのを待って下さい。表示された画像は、ドップラー効果のために上から下まで斜めになっているでしょう。PLL未使用の場合にこれは正常です。
.PP
[Image]にある
[Slant Correction...]
を選んで下さい。画像上部を表示し、画像中の縦側の斜線上でマウスボタンを押したまま、画像の一番下まで赤線を引いて下さい。同じ線上にマウスポインタがあることを確認して、ボタンを放して下さい。
.PP
割り出されたサンプリング割合が表示されるでしょう。WXtoImgは、全ての衛星にサンプリング割合を割り出します。この割合は未だ有効ではないので、[Estimate and set sampling frequencies for all satellites]
に印を付けて選び、[Set]を押して下さい。
.PP
次に、[Options]にある
[Disable PLL]
の印を外して下さい(この機能を選んでいない状態にし、PLLを使います)。再解析された
画像は、真直ぐになるでしょう。
.PP
まだ斜めならば、[Options]にある
[Disable PLL]
に印が無いことを確認して下さい。それでも画像がまだ傾斜するならば、もう一度上記の方法を再確認しながら行って下さい。
.PP
WXtoImgを終えると、割り出したサンプリング割合の指定は、保持されます。でも念のため、[Options]にある[Save Options]
を選び、サンプリング割合を保存しましょう。
.PP
衛星ごとにサンプリング割合を決めるならば、
[Set only XXX sampling frequency]
に印を付けて選びましょう。厳密なサンプリング割合を必要とするのは、Meteosat衛星とOkean衛星です。
.PP
.SH 著作権
Copyright (c) 2001-2004 Central North Publishing Limited. All rights reserved.
.PP
著作権は、 2001-2013年 Central North Publishing Limitedが全て保有します。
Translated by Nakato Mikiya (中藤 幹也).
