.\" -*- nroff -*-
.\" Copyright (c) 2001-2004 Central North Publishing Limited.
.\" All rights reserved.
.\"
.TH WXTOIMG UPGRADE  "version 2.7.3"
.SH Upgrade版について
.B Upgrade版にするには、どうしたらよいですか?
.br
次のURLを見て下さい。
.nf
    http://www.wxtoimg.com/reg/
.fi
.PP
そして、URLにある内容を追って下さい。少額な料金で追加機能が使えるように、個人用のupgrade keyが送られます。
.PP
.TP 10
.PP
.B 私はUpgradeしないといけませんか?
.br
Upgradeをすると機能が追加され、疑似立体画像用の眼鏡が送られます(立体3次元増強を見るのに必要です)。また、Upgrade版は開発を支援します。
.PP
Upgrade版には、Standard版とProfessional版があります。
.PP
.B Standard版を購入すると、何が追加されますか?
.br
疑似立体表示が追加されます。これは雲層を見るために効果を発揮します。赤/青眼鏡で見ます。
.PP
雲温度を重ね合わす増強が追加されます。
.PP
狭い中間周波数帯域幅を持つ受信機(スキャナや無線機)用に改良された機能が追加されます。
.PP
ウェブページの構成などを思うままにできます。
.PP
メルカトル図法を含む多くの地図投影法や追加機能(中心経度、規模と境界等)が、APT画像に使えます。
.PP
雲の移動が見られる極軌道衛星の動画を作ることができます。
.PP
複数の衛星画像から成る広範囲な画像が作ることができます。
.PP
明暗差を変えたり、白黒多諧調画像に変えたり、画像の傾きを変えることができます。
.PP
GPS(NMEA形式)が、自動に受信位置の緯度と経度を指定できます。
.PP
現地時間が、世界標準時に代わり表示ができます。
.PP
APT画像ではマウスカーソル下の緯度と経度、受信位置からの距離(方位角も)が表示ができます。
.PP
画像の案内を、好きな文字の大きさと色で表示できます。衛星名、通過時刻など詳細な掲載が自動にできます。
.PP
WXtoImg操作項目を画面上の好きな場所に置けます。増強や各機能選択の操作が容易にできるでしょう。ただし、MacOSでは使えません。
.PP
FT-847、PCR100/PCR1000、R2FX、SAN-200、WRX-137、AOR、Uniden製Bearcat、ICOM製とケンウッド製などの受信機を制御できます。
.PP
録音や解析を全て自動に行います。
.PP
今後改良される機能も使えるでしょう。
.nf
    http://www.wxtoimg.com/#features
.fi
.PP
注意!! Standard版もFreeware版も商用目的には使えません。
.PP
.B Professional版を購入すると、どのような機能が追加されますか?
.br
Professional版では、Standard版の全ての機能に加えて、次が追加されます。
.PP
地理変形に使う再抽出処理を追加します。
.PP
雑音フィルタ機能を追加します。
.PP
明暗差機能を追加します。
.PP
商用目的のために使用することができます。
.PP
.B 貴方に感謝いたします。
.br
次のURLで貴方も"Upgrade"をどうぞ...
.nf
    http://www.wxtoimg.com/reg/
.fi
.PP
.SH 著作権
Copyright (c) 2001-2004 Central North Publishing Limited. All rights reserved. 
.PP
著作権は、 2001-2013年 Central North Publishing Limited が全て保有します。
Translated by Nakato Mikiya.
.PP
