.\" -*- nroff -*-
.\" Copyright (c) 2001-2004 Central North Publishing Limited.
.\" All rights reserved.
.\" Translated by Nakato Mikiya
.\"
.TH WXTOIMG GUI  "2.7.3"
.SH Introduction (WXtoImgの紹介)
\fIWXtoImg\fPは、気象衛星からの信号を自動に受信し、解析や画像編集と表示をするソフトウェアです。
.br
\fIWXtoImg\fPは地表図を表示します。また、高度な色増強、3次元表示、動画、複数衛星画像、多数の地図投影法変換(例えばメルカトル図法)、画像中の文字表示、ウェブページの自動作成、温度表示が行えます。
/br
さらに、多くの気象衛星用受信機や無線機、広域受信機を制御できます。
.PP
\fIWXtoImg\fPは、極軌道衛星からのAPTと、静止衛星からのWEFAX送信を扱えます。また、\fIWXtoImg\fPは、他の画像処理のために未処理の画像保存ができます。これは、JPEG、PNG、BMP、PBM(PGM/PPM/PNM)とAVI形式です。
.PP
\fIWXtoImg\fPは、中間周波数帯域幅がかなり狭い受信機(例えば、帯域幅が狭い広域受信機)でも、画像を作ることができます。
.PP
\fIWXtoImg\fPは画像を正確に補正し、受信信号の強さのむらを無くし、衛星通過中の利得調整(AGC)にNOAA,APT画像にある遠隔測定データを使います。また、遠隔測定データは、非常に正確な温度測定表示の補正にも使われます。
.TP 10
訳者端書き: telemetry、遠隔計測
NOAA衛星APT(自動画像伝送)では、画像を作る基本になる情報も送信しています。「テレメトリフレーム(又はグレイスケール)」と呼ばれる部分には、「階調」、「チャンネル識別」、「黒体温度(後記)」が含まれています。
.TP 10
テレメトリフレームの詳細は、NOAA KLM User's Guideを参照して下さい。
.nf
    http://www2.ncdc.noaa.gov/docs/klm/html/c4/sec4-2.htm
.fi
.PP
.PP
GOES衛星では、テレメトリフレームの白黒多諧調(grayscale)が、信号の強さのむらを修正し、さらに画像を標準化するために使用されます。温度測定は赤外線画像上で行われます。
.PP
他の衛星では、テレメトリフレームの白黒多諧調と白黒線が、利得調節に使われます。
.PP
\fIWXtoImg\fPは、ドップラー効果を修正し、雑音が非常に多い信号でも正常なNOAA衛星画像を作る為にPLLを使用します。位相同期信号
(Burst cycle PLL)
は、Meteor衛星とResurs衛星でもドップラー効果の修正に使われ、傾きの無い真っ直ぐな画像を作ります。
.PP
.SH Status and Information Lines (画面表示について)
WXtoImg画面には、いくつかのタブがあります
(Image、Audio Files、Raw Images、Saved Images)。
Upgrad版には"Composites"と"Animations"が追加されます。最初の"Image"タブはWXtoImgの主画面です。受信中の画像と解析された画像が表示されます。他のタブには、WXtoImgが作った音声ファイルや未加工画像、保存画像、動画の縮小表示がされます。
.PP
貴方が、WXtoImgの保存場所に手動で移した画像や音声ファイルは表示されません。各タブにある縮小表示をクリックすると、そのファイルが表示されます。各タブ表示は、一日分(あるいは一週間や一月)の衛星通過を簡単に見ることができます。
.PP
WXtoImg画面の上側には、画像の案内が表示されます。そこには衛星名、日付及び録音開始時刻(世界標準時)を表示しています。APT衛星では、飛行方向、最大高度角及びその方位(E又はW)が表示されます。
.br
NOAA,ATP衛星では2つのチャンネル画像が表示されます。WEFAX画像については、ディジタルヘッダ情報も(利用可能な場合に)表示されます。
.PP
WXtoImg画面の下側には、2段の欄があります。一番下側の欄は、WXtoImgが行っている動作、警告と時々手がかりを表示します。
.PP
上側の欄は、左端に世界標準時を表示し、右側はいくつかに分かれています。そこには、マウスカーソル下の衛星仰角、方位角、画像座標を表示します。衛星受信時には、衛星の位置を表示します。その他に注意や案内を表示します。
.PP
その右側は、マウスカーソル下の緯度と経度(WGS84)です。次は、受信位置からの距離と方位角です。
.PP
その次は温度表示です。NOAA又はGOES画像では、マウスカーソル下の温度を表示します。温度の単位(C,F,K)は[Options]にある[GUI Options]の中で替えられます。
.PP
温度表示の右側に秒表示があります。これはマウスカーソル下の録音開始からの経過時間を示します。画像解析の位置指定をする
[Partial Decode]
を使う時に、この秒数を使います。
.PP
右端は画像解析時の音量です。録音中にも音量を表示します。通常は音量が、50.0から75.0の範囲になるように、音量を調整して下さい。詳細は、[Help]にある
[Required Calibration]
を参照して下さい。
.PP
.SH File (読出し、書込み、表示)
解析するファイルを選び、解析したり、画像の保存をする時に使います。
.TP 10
\fIOpen Audio File...\fP
解析をする音声ファイルを選びます。[Options]にある[Disableauto-decode]が選ばれていないと、解析は自動に始まります。解析に使われる音声ファイルは、AU(.au)、WAVE(.wav)、8ビット符合無しLSB、16ビット符合付きのLSBです。これらは、毎秒11,025のサンプリング周波数でPCM形式に変換されたものです。
WXtoImgは、8ビット、16ビット又は32ビットサンプルが使えます。しかし8ビットは、高品質な画像を作るのに十分ではありません。ですから、16ビットサンプリングを使うことを強くお勧めします。音声ファイルは、モノラルになります。ステレオ(又はマルチチャンネル)が使われる時は、1つのチャンネル以外は使いません。モノラル信号を使うことをお勧めします。
.TP 10
\fIOpen Raw Image...\fP
WXtoImgは、PNG,PBM(PGM)とNOA形式を読み込めます。これらの処理は、音声ファイルよりも早いです。[Options]にある
[Disable auto-decode]
が選ばれていないと、解析は自動に始まります。
NOA形式は、衛星受信機が作ります。PNG、PBM(PGM)、NOA画像は、16ビットのグレイスケールを含みます。
JPEG,BMP画像とAVI形式は、WXtoImgでは読み込めません。PNG,PBM(PGM)とNOAの処理には、[Resync]、[Interpolate]、
[Disable PLL]
等の機能とサンプリング周波数は、使われません。音声ファイルの解析にのみこれらの指定が使われます。
.TP 10
\fISave Image as...\fP
表示中の画像を保存します。保存形式(JPEG,PNG,BMP,PNM,AVI)は、拡張子で決まります。貴方が拡張子を使わない場合や、形式を1つのみ扱うならば、[Options]にある
[Image and Movie Options...]
で形式の指定ができます。
.TP 10
\fIComposite Image to...\fP
表示中の画像を保存します。既に画像があり、それに上書きすると、元の画像に重ね合わせて保存します。地図投影法は"Normal"以外を選び、[Options]の
[Projection Option]
で、画像範囲の緯度・経度を指定しましょう。複数の衛星画像から成る、広範囲な画像が作れます。
.TP 10
\fISave Raw Image as...\fP
16ビットPNG形式の画像を保存します。PNG形式画像は、
[Open Raw Image...]
で読み込み、画像処理ができます。この画像処理には、[Resync]、[Interpolate]、[Disable PLL]
の機能とサンプリング周波数は使われません。
.TP 10
\fIMixer Control...\fP
録音元を選び、録音の音量を確認します。
.TP 10
\fIRecord...\fP
受信録音を始めます。
ここでは、録音のみか画像解析も行うか、音声ファイルとraw画像の保存の有無を指定します。また、画像の保存方法や動画作成の指定をします。これらの指定は、
[Auto Process]
にも使われます。使用する増強、画像や動画の保存名それぞれは、ボタンを押しその中で指定します。どのような名前になるかは、"FilenameTemplate(保存名形式)"をご覧下さい。
録音方法(サンプルビット)、スケルチの深さ、録音する衛星高度などは、[Options]にある
[Recording Options...]
で変更ができます。録音(解析も)は、[File]にある[Stop]を押して止めるまで続きます。
[Minimum percent of projection filled]
(Upgrade版のみ)は、画質により保存の有無を指定します。これは、解析された画像ピクセルが、指定した割合未満ならば画像の保存や動画に追加をしません。作られる画像が表示範囲に対して、この割合を満たさないと画像が保存されません。初めは、0.1%です。
[Minimum solar elevation for visible images]
(Upgrade版のみ)は、太陽高度により保存の有無を指定します。可視光線センサを使う画像が、指定された太陽高度未満ならば、保存しません。"0.0"の指定は、太陽高度にかかわらず画像が保存します。
.TP 20
          \fIRecord only (show image if enabled)\fP
[Options]にある
[Recording Options]
の指定により衛星の受信録音をします。
[GUI Options...]
中で
[Shown image while recording]
を指定すると、未処理の画像が録音中に表示されます。録音後に補足処理はしません。
これらの録音した音声ファイルは、[File]にある
[Open Audio File...]
から選ぶか、あるいは、
"Audio Files"
タブ中の小表示をクリックすると再解析されます。
.TP 20
          \fIRecord and auto process\fP
[Options]にある
[Recording Options]
の指定により衛星の受信録音をします。録音後に、[Enhancements]、[Options]、[Projection]の指定で解析します。多くの機能を使い、画像や動画、合成画像、ウェッブページを作ります(FAQの「ウェブページを作る」を参照して下さい)。これらの指定は、[File]にある
[Auto Process]
にも使われます。処理が終わると、録音ファイルや地表図は消されます。(もちろん、残すこともできます)
.TP 10
\fIDecode\fP
解析をします。
録音ファイルを選んだり、衛星の飛行方向、画像処理を替えると自動に解析が始まります。[Options]にある
[Disable auto-decode]
を選ぶと、解析は自動には始まりません。[Options]にある各機能や衛星を他に替えたならば、[File]の[Decode]を押して解析をしましょう。
.TP 10
\fIPartial Decode\fP
上記の[Decode]と似ていますが、指定した範囲を解析します(解析範囲に録音経過時間(秒)を入れます)。これは、録音ファイルが2つ以上の衛星信号を含む場合に有効です。また、雑音が無い部分のみの画像を作るのに便利です。
[Text Options]
を使うならば解析後に表示されるので、[Image]にある[Crop]を使い画像の範囲を限るよりも、この機能を使うのが良いでしょう。
.TP 10
\fIAuto Process\fP
[File]にある[Record]の指定により、画像解析と保存や動画にコマを追加します。録音ファイルや地表図を録音方法で削除する指定になっていても、各ファイルを消しません。
.TP 10
\fIView Image...\fP
画像を表示します。
PNG,JPEG,BMP,PBM(PGM/PPM)形式が表示できます。[Image]にある各機能は使えますが、[Enhancements]と[Options]の各機能は使えません。画像処理後は[File]にある
[Save Image as...]
で画像を保存します。WXtoImgが作った画像ならば、[Projection]を使い地図投影法を替えられるでしょう。
.TP 10
\fIView Movie...\fP
AVI動画を表示します。表示には、MS-Windowsでは、DirecX8.0版以上が必要です。(Windows-XPには、DirectXが既に組み込まれています)
.nf
    http://www.microsoft.com/directx
.fi
.PP
*NIXでは xanimが必要です。
.nf
    http://xanim.va.pubnix.com/home.html
.fi
.PP
.TP 10
\fIUpdate Web Page\fP
今あるウェブページを公表します(FTPを使います)。その際は、ウェブページに画像を加えません。これが使えるのは、[File]にある[Record]内の
[Web Page Settings]
にある
[Automatically FTP as images are added]
が選ばれていないときです。ダイアルアップ接続などを行い、ウェブページを手動で転送するときに使います。
.TP 10
\fIImage Properties...\fP
表示している画像に関する情報を表示します。
.TP 10
\fIProcessing Info...\fP
画像処理中にWXtoImg画面下側に表示した案内の全て表示します。
.TP 10
\fIUpdate Keplers\fP
インターネットに接続し、www.celestrak.comから気象衛星の最新軌道要素を取り入れます。軌道要素は、受信と地表図のために更新する必要があります。古い軌道要素は、ずれた地表図を表示します。地表図を表示には、軌道要素の更新を少なくとも毎週することをお勧めします。正確な地表図表示をするならば、毎日か日に二度の更新をお勧めします。
.TP 10
訳者端書き: 
もしも、気象衛星画像と地図がずれるならば、この
[Update Keplers]
と貴方のコンピュータ時計と標準時のずれを確認して下さい。
.PP
.TP 10
\fIPass List...\fP
現在の時刻から指定された先まで(初めは一週間)に予定される衛星通過を表示します。これは、[Options]にある
[Active APT Satellites]
に選ばれている衛星を表示します。さらに、
[Recording Options]
の指定にもよります。
.TP 10
\fIClear\fP
表示されている画像を消します。画像の保存を求めずに消すので、注意して下さい。間違えて消してしまったならば、元の録音や未処理の画像から画像を使って、もう一度表示できます。
.TP 10
\fIStop\fP
録音又は解析が完了する前に止めます。
.TP 10
\fIExit\fP,\fIQuit\fP
WXtoImgを終えます。MacOS Xでは、WXtoImgに"Quit"はありません。
.PP
.SH Direction (飛行方向)
[Enabled expert mode]([GUI Options]の中にあります)を使うと、次の機能が表示されます。
極軌道衛星の飛行方向を指定します。WEFAXの画像処理では、この指定は使いません。地表図と地図投影法が使われるならば、WXtoImgが飛行方向を決めるので、ここでの指定は使われません。
.TP 15
\fIAutodetect\fP
WXtoImgは、衛星の飛行方向を決める為に受信記録ファイルが作られた時刻を使います。ですから、この機能はコンピュータ内部時計が、時間帯(例えば日本標準時)に正確に合っていないと旨く働きません。時計がかなりずれていたり、受信場所が極付近にあると旨く働きません。さらに受信記録とその日付が、衛星通過の所要時間と同じ必要があります。
.TP 15
\fISouth->North\fP
北向き飛行(昇順)。衛星は南から北へ飛行します。この時、画像は180度回転しています。NOAA,APT画像は、画像にはチャンネルAとBの両方があります。
.TP 15
\fINorth->South\fP
南向き飛行（降順)。衛星は北から南へ飛行します。
.PP
.SH Satellite (衛星)
解析する衛星を選びます。極軌道衛星については普段は、
[Autodetect APT]
を指定します。静止気象衛星は、[GOES]や[Meteosat]や[GMS]のいずれかを選びます。
.PP
受信機の制御が行えず、複数の衛星が通過する際に、他の違う衛星が記録される場合や、他のプログラムによる不正確な日付の古い音声ファイルを解析する場合は、特定の衛星を選びましょう。
[Options]にある[GUI Options]
内の
[Enable expert mode]
を使うと、以下にある衛星機種ごとの機能が使えます。
.TP 10
\fIAutodetect APT\fP
極軌道衛星からのAPT画像のみを解析します。これは衛星の判別を早めます。
.TP 10
\fIMeteosat\fP
Meteosat静止気象衛星からのWEFAX画像を解析します。
.TP 10
\fIGOES\fP
NOAA静止気象衛星(GOES)からのWEFAX画像を解析します。
.TP 10
\fIGMS\fP
静止気象衛星(GMS)からのWEFAX画像を解析します。
.TP 10
\fIAutodetect\fP
これは、受信信号と画像処理から衛星を自動選択します。
以下の機能は
[Enable expert mode]
を使うと表示されます([Options]中[GUI Options]にあります)。
.TP 10
\fIAutodetect WEFAX\fP
静止衛星からWEFAX画像のみを解析します。これを選ぶよりも、特定の衛星(GOES, Meteosat)を選ぶと良い結果になるでしょう。
.TP 10
\fINOAA\fP
極軌道NOAA衛星からのAPT画像を解析します。
.TP 10
\fIMeteor (series 3)\fP
ロシアのMeteor3のAPT画像を解析します。
.TP 10
\fIMeteor (series 2)\fP
ロシアMeteor2のAPT画像を解析します。
.TP 10
\fIResurs\fP
ロシアResurs衛星のAPT画像を解析します。
.TP 10
\fIOkean\fP
ロシアOkean衛星のAPT画像を解析します。
.TP 10
\fISICH\fP
ロシアSICH衛星のAPT画像を解析します。
.TP 10
\fINOAA 12\fP
極軌道NOAA衛星のAPT画像を解析し、海表面温度測定をNOAA12号に指定します。海表面温度測定が使われないならば、これは上記"NOAA"と同じです。
.TP 10
\fINOAA 14\fP
極軌道NOAA衛星のAPT画像を解析し、海表面温度測定をNOAA14号に指定します。海表面温度測定が使われないならば、これは上記"NOAA"と同じです。
.TP 10
\fINOAA 15\fP
極軌道NOAA衛星のAPT画像を解析し、海表面温度測定をNOAA15号に指定します。海表面温度測定が使われないならば、これは上記"NOAA"と同じです。
.TP 10
\fINOAA 16\fP
極軌道NOAA衛星のAPT画像を解析し、海表面温度測定をNOAA16号に指定します。海表面温度測定が使われないならば、これは上記"NOAA"と同じです。
.TP 10
\fINOAA 17\fP
極軌道NOAA衛星のAPT画像を解析し、海表面温度測定をNOAA17号に指定します。海表面温度測定が使われないならば、これは上記"NOAA"と同じです。
.PP
.SH Enhancements (増強)
訳者端書き: 反射と放射について
植物は近赤外線(NOAA,ch2)の反射がとても強く、水は近赤外線の反射が弱い性質です。また植物は、黄緑色の光や青色の光では反射が強い性質です。植物と水の反射特性は逆です。
.PP
ですから、ある場所の近赤外線反射が強く、黄緑色光や青色光の反射が弱いと判ると、そこには植物があると考えられます。
.PP
ここにある各増強(Enhancements)は、可視光線画像や近・遠赤外線画像をそれぞれ較べて処理を加え画像を表示します。
.PP
遠赤外線では、物体表面の温度に比例した放射から温度が測定できます。
.PP
それぞれの増強曲線を表示しながら、以下の説明文を読み進めるのも良いでしょう。増強曲線は[Image]にある[View Enhancement Curve]で表示します。
.PP
各増強(Enhancements)の画像例は次のURLにあります。
.nf
    http://www.wxtoimg.com/pics/
.fi
.PP
.PP
増強補正は、多様な強調をします。[Options]にある
[Disable auto-decode]
を選ばない限り、増強を替えると解析は自動に始まります。
.PP
.TP 15
\fINormal\fP
[Gamma]、[Sharpening]、[Despeckling]やその他の指定を使い、増強をしない画像を表示します。
.TP 15
\fIPristine\fP
未処理な画像を表示します。この画像は、他の画像ソフトが行う画像処理の為に増強がされていません。この様に一般化された画像は、画像ソフトウェアとって元のデジタルデータよりも役立つでしょう。温度によって作られた赤外線画像は、一般化はされません。この機能は、[Option]にある[Gamma]、[Sharpen]、[Despeckle]、[rotation]やその他の増強を使いません。
.TP 15
\fIContrast enhance\fP
[Options]にある[Contrast]の指定を使って、明暗差増強をします。
.TP 15
\fIBlack and white\fP
黒と白の画像を作ります。暗いピクセルは黒に、明るいピクセルは白に替えます。
.TP 15
\fIContrast enhance (NOAA ch A only)\fP
明暗差増強を、NOAAチャンネルA画像のみに行います。他の画像は表示しません。
.TP 15
\fIContrast enhance (NOAA ch B only)\fP
明暗差増強を、NOAAチャンネルB画像のみに行います。他の画像は表示しません。
.TP 15
\fIMCIR map colour IR (NOAA)\fP
海を青色に、地表を緑色にするために、NOAAセンサ4の赤外線画像を使います。高い雲は白く、低い雲は灰色に、地表と海を有色にし雲を明るく見せます。しかし、地表と海及び低い雲の区別は難しいかもしれません。暗い色は、より暖かい部分を示します。
.TP 15
\fIMCIR with precipitation (NOAA)\fP
上記のMCIRに、高高度にある低温の雲にNO増強と同じ色をつけて表示します。(この説明は原文にはありません)
.TP 15
\fIMCIR anaglyph false 3-D (NOAA-# 2-4)\fP
上記のMCIR使って疑似立体画像を表示します。(この説明は原文にはありません)
.TP 15
\fIMSA Multispectral analysis (NOAA-# 2-4)\fP
多重波長解析は、NOAAチャンネル2画像とチャンネル4画像の分析に基づき、どの領域が雲や地表か海かを判断します。その結果、鮮明な疑似色画像を表示します。疑似色を付ける機能が、[Options]の
[Image and Movie Options...]
にあります。この増強は調色(パレット)を使いません。また、温度表示は一般化されたものではありません。
.TP 15
\fIMSA with precipitation (NOAA-# 2-4)\fP
上記のMSA(多重波長解析)と同じですが、高高度にある低温の雲にNO増強と同じ色をつけ、降水確率の目安となる表示をします。
.TP 15
\fIMSA anaglyph false 3-D (NOAA-# 2-4)\fP
上記のMSA多重波長解析と同じですが、疑似立体画像(赤/青眼鏡で見ると立体表示になります)を作ります。Upgrade版のみ使えます。
.TP 15
\fIHVCT false-colour (NOAA 2-4)\fP
下記のHVCと同じですが、水表面とその色は、地表面温度以上に表現されます。
.TP 20
訳者端書き : HVC、マンセルシステム
アメリカのアルバート・H・マンセル(1858-1918)が創案した表色系です。色相(Hue)、明度(Value)、彩度(Chroma)を元に色を配列しています。
.PP
.TP 15
\fIHVCT with precipitation (NOAA 2-4)\fP
下記の
[HVCT false-colour]
と同じですが、降水確率が高くなる高高度にある雲の頂点には、
NO enhancement
と同様に色付けをします。
.TP 15
\fIHVC false-colour (NOAA 2-4)\fP
HVC色系を使って、温度に基づいたNOAA,APT画像から疑似色画像を作ります。色調はセンサ4画像を元にした温度を使い、明るさはヒストグラム均一化されたチャンネルA画像の色彩度を使います。
HVC色系は、異なる色の同じ明度(value)は、同じ輝度であるように表現され、色の間隔は同じように見えます。HVC色系では、明るい領域は不飽和になります。
[Use other sensor]
を使うと、チャンネルB画像の色彩度を使います。
.TP 15
\fISea surface temp (NOAA-# 3-4)\fP
海表面温度に基づくNOAA,APT画像から、疑似色画像を作ります。疑似色にする為にセンサ3とセンサ4画像を元にした、海表面温度を使います。海と雲と地表の識別はしません。海表面温度は、ピクセル中にある薄い雲や小さい雲や、信号の雑音があると不正確になるでしょう。海表面温度補正は、NOAA衛星の仕様を知る必要があります。ですから、この増強を使う時は特定のNOAA衛星を、[Satellite]から選びましょう。この増強に限り表示される温度は、海表面温度アルゴリズムを使用し計算されます。
.TP 15
\fIDaylight sea surface temp (NOAA)\fP
太陽光海表面温度(NOAA)は、海表面温度に基づいたNOAA,APTの画像から疑似色画像を作ります。疑似色にする為にセンサ4画像を元にした海表面温度を使います。これは、センサ3とセンサ4を使う上記の海表面温度(NOAA-#,3-4)ほど正確でありませんが、センサ3とセンサ4画像が使えない時に有効です。海表面温度は、ピクセル中にある薄い雲や小さい雲や、信号の雑音があると不正確になるでしょう。
.TP 15
\fIVegetation (NOAA 1-2)\fP
NOAA,APTセンサ1とセンサ2画像を使います(これは衛星打ち上げ後のテスト期間中に使われます)。植物分布画像を作り、地表は緑色、水は紺色、雲は白色にします。この増強は調色(Palette)を使わず、また温度標準を用いません。
.TP 15
\fIAnaglyph false 3-D (GOES/NOAA)\fP
雲の高度を知る為にチャンネルA画像から、疑似立体表示(赤/青眼鏡で見ると立体画像になります)を作ります。
[Use other sensor]
が選ばれると、チャンネルB画像から作ります。この機能はUpgrade版のみ使えます。
.TP 15
\fIColour anaglyph false 3-D (NOAA)\fP
NOAA衛星の組み合わせた画像を使い、HVCT増強の色彩に基づく疑似立体表示(赤/青眼鏡で見ると立体画像になります)を作ります。
[Use other sensor]
が選ばれると、チャンネルB画像のみで疑似立体画像を表示します。この機能はUpgrad版のみ使えます。
.TP 15
\fIClass enhancement (NOAA)\fP
このNOAA,APT画像は、最適化集合体を作る処理を繰り返し使います。チャンネルAとチャンネルB画像の両方に同様の特性を持つ27までの画素(ピクセル)の集まりが作られます。この分類は、ヒストグラム均一化されたチャンネルA画像を色付けるために使用されます。
.TP 15
\fINO colour IR enhancement (GOES/NOAA)\fP
これは、NOAA赤外線明暗差増強です。非常に暗い地表と海面域の明暗差を大幅に増し、低温度の雲上部に色をつけます。地表と海面の詳細を表示し、雲上部温度が判る表示を行います。この増強は温度標準を用います。
.TP 15
\fIZA general IR enhancement (GOES/NOAA)\fP
これは、NOAAの一般的な気象用赤外増強機能です。温度情報がほとんど無い極低温度(-60度以下)と高温度(30度以上)の部分は、両方を極端にすることで明暗差強調がされます。この増強は温度標準を用います。
.TP 15
\fIMB thunderstorm (GOES/NOAA)\fP
低温度の雲上部に対する増強です。最も強い降雨が、雷雨のどこに生じているかを示すのに役立ちます。この増強は温度標準を用います。
.TP 15
\fIMD warm season MB (GOES/NOAA)\fP
NOAA,MD増強は、一般に広く使われるMB増強を修正したものです。これは暖かい季節に使うことを目的とし、増強曲線の-35度から-60度の"くさび状"の範囲に、増強した画像を表示します。
もう一方で、暖かく低い雲(30度から7度の範囲)に増強をします。この部分にある雲の範囲はMBより多少広く、増強は弱めです。この増強は温度標準を用います。
.TP 15
\fIBD hurricane (GOES/NOAA)\fP
これは、NOAA熱帯低気圧(ハリケーン、台風、サイクロン、ウイリー・ウイリー)増強です。熱帯低気圧の強さに関連がある「目」と、その回りの「雲の壁」の特定な温度を最も明るく表示します。この増強は温度標準を用います。
.TP 15
\fICC enhancement (GOES/NOAA)\fP
NOAA,CC増強曲線。この増強は温度標準を用います。
以下のCC,EC,HE,HF,JF,JJ,TA,WV増強は、
[Enable expert mode]
を使うと表示されます([Options]中[GUI Options]にあります)。
.TP 15
\fIEC enhancement (GOES/NOAA)\fP
NOAA,EC増強曲線。この増強は温度標準を用います。
.TP 15
\fIHE western US (GOES/NOAA)\fP
NOAA,HE増強は、主にアメリカ西部の気象業務に使われます。多種な雲に合う増強を行いますが、多少複雑で初めは使いづらいかもしれません。これは、北アメリカ太平洋沿岸に沿う低温度と中温度の雲を2つの灰色で増強します。
結氷温度は容易に見極められ、氷結温度を重視する航空関係者に利用されます。増強曲線にある"くさび状"の部分は、雷雨と前線の仕組みに関係する極低温の赤外線雲上部の5度ずつ-60度の範囲にある温度を表示します。追加される2つの灰色色調の部分は、-60度より低温の雲上部温度を示します。この増強は温度標準を用います。
.TP 15
\fIHF new western US (GOES/NOAA)\fP
NOAA,HF増強はH系列の主流で、主にアメリカ西部の気象業務に使われます。北アメリカ太平洋沿岸に沿う低温度と中温度の雲を増強します。
増強曲線にある"くさび状"の部分は、雷雨と前線の仕組みに関係する極低温の赤外線雲上部の5度ずつ-60度の範囲にある温度を表示します。この増強は温度標準を用います。
.TP 15
\fIJF simple sea surface/cold cloud (GOES/NOAA)\fP
NOAA,JF増強は、海表面温度と雷雨や他の天候に関係する低温度の雲上部を強調する複合型増強系列です。これは、後記のJJ増強よりは単純です。低温度(-33度未満)部分の増強は、MB増強とほとんど同じです。
海表面温度を表示するために、10度から25度の範囲と、熱帯と亜熱帯領域の暖かく低い雲に最大の増強をします。この増強は温度標準を用います。
.TP 15
\fIJJ sea surface/cold cloud (GOES/NOAA)\fP
NOAA,JJ増強は、海表面温度と雷雨や他の天候に関係する低温度の雲上部を強調します。海表面温度を表示するために、10度から25度の範囲と低い雲に最大の増強をします。
結氷温度の有無は、航空関係者にとって重要です。雷雲のような低温の雲上部を、複数の尖った変化に富む増強曲線を用いて詳細に表示します。でも、精度良く温度を測定することは難しいでしょう。この増強は温度標準を用います。
.TP 15
\fILC fog/low cloud/precip (GOES)\fP
NOAA,LC曲線は、GOESの3.9ミクロン赤外線チャンネル(チャンネル2)画像に使われます。霧や低い雲が生じる典型な温度範囲(-9度から36度)を最も増強します。別に、中緯度帯の降雨に関わる-10度から-29度の温度範囲を増強します。
チャンネル2が"温点"に敏感なので、白く表示される火災などを48度から60度の範囲にある増強曲線が見つけることができます。-30度から-67度の範囲は機器が発する雑音のために、増強はしません。この増強は温度標準を用います。
.TP 15
\fITA enhancement (GOES/NOAA)\fP
NOAA,TA増強曲線。この増強は温度標準を用います。
.TP 15
\fIWV water vapour (GOES)\fP
修正されたNOAA,WV曲線は、GOESの6.7ミクロン水蒸気チャンネル(チャンネル3)に使われます。-5度から-90度の範囲のみを増強します。-90度以下の温度は白色に、-5度以上の温度は黒として表示します。この増強は温度標準を用います。
.PP
.SH Options (機能選択)
様々な機能を選びます。WXtoImgの使い初めには、切り替えて使う機能は使われていません。[Gamma]、[Sharpen]、[Despeckle]の標準な指定は、星印で示されます。+印はお勧めの指定を示します。
.TP 10
\fIDisable auto-decode\fP
増強や衛星の飛行方向などの指定を替えた時に、WXtoImgが自動に解析を行わないようにします。
.TP 10
\fIInterpolate\fP
過剰サンプリング(50%拡大画像)を行い、画像の表示を変えます。垂直方向と水平方向のサンプリング割合を増やし、拡大画像を作ります。
NOAA画像では、チャンネルB画像も衛星の移動とサンプリング方法を補うためにサンプリング割合を下げます。これは画像間の表示を良くし、複数帯域の解析を行い質を高めます。
この機能は、
[Enable expert mode]
を使うと表示されます([Options]中[GUI Options]にあります)。
.TP 10
\fIUse other sensor\fP
解析される画像の可視光領域の代りに、他の波長領域を使います。HVCとHVCT及び立体増強が使うチャンネルA画像の代わりに、可視光領域としてチャンネルB画像を使います。
.TP 10
\fIDisable PLL\fP
位相同期ループ(PLL)を止めます。これは、サンプリング割合の微妙な変化やドップラー効果により画像が斜めにさせない機能を停止します。この機能は、位相同期を扱えない受信機を使い、Meteor衛星とResurs衛星からの低品質な信号を解析する時に役立つでしょう。
.TP 10
\fIShow All\fP
雑音の多い部分や音量が低い信号の部分からは、画像を作りません。画像端を見る[Crop telemetry]を参照して下さい。
.TP 10
\fICrop telemetry\fP
画像端にあるテレメトリフレームを表示しません。
.TP 10
\fIResync\fP
画像に再同期します。低いS/N比の音声ファイルや、狭い中間周波数帯域幅(広域受信機や無線機)の録音ファイルにある時刻情報を扱いません。この為に、かなり壊れた画像を元にし、修正された画像が表示できるかもしれません。この機能は良好な画像には問題を起こしやすいので、普段は使わないで下さい。
この機能は、
[Enable expert mode]
を使うと表示されます([Options]中[GUI Options]にあります)。
.TP 10
\fIDisable Map Overlay\fP
地表図を表示しません。地表図表示には最新の軌道要素が必要です。
[File]の
[Update Keplers]
を参照して下さい。地表図を非表示にしても地表図作成は行われます。
[GUI Options]
の[Enable map and projection support]も参照して下さい。
.TP 10
\fINoise filter\fP
雑音ろ過をします。これは、5x5画素の周辺を中心部に変換します。ですから画像をかなりぼかします。
この機能は、
[Enable expert mode]
を使うと表示されます([Options]中[GUI Options]にあります)。
.TP 10
\fIContrast\fP
HVC、HVCT、MSAと植生増強(Vegetation)に使う明暗差増強の種類を選びます。Upgrade版で使えます。[Hist_Eq]はヒストグラム平均化です。[Linear(constant)]は、衛星センサによってのみ変わる一定の線形増強です。[Linear(variable)]は、可変の線形増強で全ての画像の為に明暗差を調整します。[None]は、明暗差増強をしません。画像が解析後に比較処理されるか画像合成をするならば、画像が全て同様になるように[Linear(constant)]か[None]のどちらかを使いましょう。
.TP 10
\fIIllumination Compensation\fP
太陽のむらのある(一様ではない)地球表面の照らし方を修正します。地球表面の鉛直から照射があるように、画像を大幅に修正します。しかし、"High"や"Med"、"Low"は完全には修正できません。"None"は修正をしません。低い太陽高度では修正の結果、雑音が増し画像が低品質になることがあります。
.TP 10
\fIGamma\fP
標準ガンマ補正です。1.00から2.50の範囲です。1.00はガンマ補正をしません。PCディスプレイについては、約1.40のガンマ補正が表示に最適なようです。マッキントッシュには1.15です。SGIには1.10、NeXTには1.00、Sunと他のコンピュータには1.40をお勧めします。
.TP 10
\fISharpen\fP
画像を鋭くする指定をします。初めは0.6です。
.TP 10
\fIDespeckle\fP
画像中の雑音の消去ができます。この機能は、
[Enable expert mode]
([Options]中
[GUI Options]
にあります)を使うと有効になります。[none]は雑音の消去を行いません。問題のある画素は、5x5範囲の画素と交換ができ、雑音と識別され中間値と取り替える、その標準偏差です。シグマを増加させると、交換される画素の数が減少します。シグマを減少させると、交換される画素の数を増加します。初めの指定は、「none」です。
ほとんどの場合に"2.0"が使えます
([Enable expert mode]
が未使用な時は"2.0"です)。低い数は画像をぼかします。
.TP 10
\fIActive APT Satellites\fP
APT送信をしている衛星を選びます。
[Options]の
[Recording Options]
にある
[Record only when active APT satellites are overhead]
を受信記録方法にすると、Activeに印を付けたAPT衛星を受信し地表図を作ります。受信機の制御ができるならば、衛星周波数(MHz)の指定ができます。
優先度(priority)も指定できるでしょう。2機以上の衛星が同時に頭上を通過する時に、優先度(1が最優先、5は最低)が高い順に選ばれて受信します。衛星の優先度が同じならば、通過高度が最も高い衛星を受信します。
[Recording Options]
の中で受信機を選ばないと、この機能は使えません。
[Update this table when updating Keplers]
が使われると、WXtoImgは[active]の衛星を選び、その衛星(インターネットに接続し軌道要素を取り込みます)の周波数に受信機を合わせます(優先度は変更しません)。
[GUI Options]
にある
[Expert mode]
に切り替えた時に、選ばれていない衛星は受信しません。
.TP 10
\fIGround Station Location\fP
受信位置を指定します。緯度と経度は、分や秒表示ではなく「度」で入力します。(北緯と東経は"+"(正の数字)、南緯と西経は"-"(負の数字))大都市名(人口10万人以上)及び国名(例えば日本は"japan")を入れて、
[Lookup Lat/Lon]
を押すと、緯度及び経度が自動に指定できます。地表図を表示したり、[Option]にある
[Recording Options]
中の
[Record only when active APT satellites are overhead]
を使うならば、この
[Ground Station Location]
を指定して下さい。
また、[Use_GPS]を指定できます。GPSがつながっているシリアルポートとボーレートを指定して下さい。不明ならば"4800"にしましょう。GPSはNMEAが出力できるか確認しましょう。GPSの説明書を参考にして下さい。この機能が使えると、WXtoImgが位置情報を必要とするときにGPSに問い合わせます。さらに、
[Set PC clock from GPS]
を選ぶと、PC内部時計をGPSを使って調整できます。この時刻合わせ機能は、GPSがNMEA2.X版を扱える必要があります。WXtoImgは、位置や地図投射法と地表図表示の為にWGS84データを使います。
貴方がGUN/Linuxをお使いならば、"root"権限で"\fI/usr/sbin/visudo\fPを行い、sudoの設定ファイル最後に
\fImyusername myhostname = NOPASSWD:/bin/date\fP
を追記ししょう。"myhostname"はお使いのコンピュータ名、"myusername"は貴方のアカウント名です。このGPS機能はUpgrade版で使えます。
.TP 10
\fIRecording Options...\fP
録音に関係する様々な機能があります。
.TP 20
          \fIRecord using WEFAX start/stop tones\fP
静止衛星(GOES,Meteosat,GMS)からのWEFAX開始信号を受け取ると録音を始めます。WEFAX停止信号があると録音は止まります。
.TP 20
          \fIRecord only when active APT satellites are overhead\fP
これを選ぶと、[Options]にある
[Active APT Satellites]
で選んだ衛星がATP送信を行っている時に録音をします。この機能は、初めに選ばれています。この録音方法は効率が良く、また録音信号を連続解析をしないので、CPU使用が最小限になります。
.TP 20
          \fIwith maximum elevation above (degrees)\fP
ここに指定した高度角度以上の衛星通過を録音します。初めは高度20度になっています。
.TP 20
          \fIrecord only when satellite is above (degrees)\fP
衛星がここに指定した角度以上にある間は待機し、指定した角度以下になると録音を停止します。初めは高度8度になっています。
.TP 20
          \fIand require\fP
録音方法を指定します。
[squelch break]
を選ぶと、音量がトリガ水準を上回るのを待ちます。
[2400Hz carrier]
を選ぶと、2400Hz搬送波が検知されるのを待ちます。どちらかの機能が選ばれると、
[finish recording delay]
が使用され、
[record only when satellite is abov]
で指定した数字を下回ると録音が止まります。[nothing]を選ぶと、衛星が上空にあり、信号があってもなくても録音をします。初めは[2400Hz carrier]になっています。
.TP 20
          \fIsoundcard\fP
録音に使うサウンドカードを選びます。Linuxでは、"/dev/dsp"になっています。(サウンドカードを追加すると"/dev/dsp1""/dev/dsp2"と表示されます)DOSとMS-Windowsでは、0になっています。(追加分は1,2などと番号付けされるでしょう)
.TP 20
          \fIantenna type\fP
Antenna type.
.TP 20
          \fIreceiver control\fP
受信機を指定します。受信機を外部制御できない場合や、コンピュータに接続しないならば[none]にして下さい。記録方法に、
[Record only when active APT satellites are overhead]
を指定しているならば、受信機制御ができます。PCR1000やPCR100を使うならば説明書を参考にして、外部制御ができるように内部ジャンパを切り替えて下さい。
ケンウッド製受信機AR3000、AR5000とAORは4800ボーレートで使えます。BC245XLTやBC895XLT、BC780XLTは、9600ボーレートで使えます。IC-R8500とIC-R10は、アドレス4Aと52を使い9600ボーレートで使えます。
制御用の外部コマンドwxctl(wxctl,wxctl.com,wxctl.exe,wxctl.bat)は、初めの引数は衛星名を、次の引数は周波数(MHz)を、次の引数は受信機のポートを送ります。チャンネルが選ばれず、また衛星名が空きならば、周波数は0.00になります。この時、一般に制御プログラムは走査状態にします。
.TP 20
          \fIreceiver port\fP
RS-232ポートは受信機制御に使われます。ポートがRS-232で使えないならば(例えばゲームポートで使っている)、この指定は無効です。
.TP 20
          \fIreceiver baud rate\fP
受信機と通信するボーレートを指定します。受信機側のボーレートを変更できないならば、この指定は使われません。その場合は、
[receiver default]
を指定して受信機のボーレートに合わせます。
.TP 10
\fIMap Overlay Options...\fP
地表図に表示/不表示と色などの指定をします。
.br
Display Land :海岸線
.br
Display Lakes:  湖
.br
Display Rivers:  河川
.br
Display Country Borders:  国境
.br
Display State/Province Borders:  州/省境界
.br
Display Ground Station:  受信場所
.br
Display Cities:  都市(人口規模)
.br
Display Lat/Lon(degrees):  緯度線/経度線(間隔)
.br
.TP 10
\fIText Options...\fP
画像に案内を表示します(Upgrade版のみ)。2個所あり、どちらか一方又は両方が表示できます。指定は"%"を含み、
[Filename Template]
にあるように書かれています。表示される色と文字の大きさ(ポイント)を一覧から選びます。表示位置は、[X:]と[Y:]に数字を入れます。数字は画素数です。正の数字は画面左端と上端から、負の数字は画面右端と下端からの画素数です。"c"は中央です。表示は複数行にできます。\fBfontsize=\fP\fI##\fP\fB\fPの数字を替えて後に続く行を、異なる文字の大きさにすると良いでしょう。
[True Type Font:]は、利用できるフォントに置き換わります。コンピュータにあらかじめ用意されたフォントを使うには、空白にして下さい。他の種類のフォントは、内蔵するフォントが標準のASCII文字(英語)だけを使用すると共に、ヨーロッパ言語とアジア言語を画像中に文字を記入するために使うこともできるでしょう。
.TP 10
\fIProjection Options...\fP
地図投影法の調整をします(Upgrade版は全て使えます)。
.TP 20
           \fIReference Latitude\fP
この緯度を地図投影法の中心にします。北緯は正の数字、南緯は負の数字です。これが画像の中心ではなく、地図投影自体の中心であることに注意して下さい。(緯度が分からないので空白にする時も)
.TP 20
           \fIReference Longitude\fP
この経度を地図投影法の中心にします。東経は正の数字、西経は負の数字です。これが画像の中心ではなく、地図投影自体の中心であることに注意して下さい。(経度が分からないので空白にする時も)
.TP 20
          \fINorth Boundary (latitude)\fP
北緯境界(緯度)。\fISouth Boundary (latitude)\fPを見て下さい。
.TP 20
          \fISouth Boundary (latitude)\fP
南緯境界(緯度)。この境界を指定すると、画像は境界で区切られ範囲の外側は表示しません。緯度と経度の全てを入れないと使えません。南半球では、負の数を入れます。"90.0"から"-90.0"の範囲です。
.TP 20
          \fIWest Boundary (longitude)\fP
西経境界(経度)。\fIEast Boundary (longitude)\fPを見て下さい。
.TP 20
          \fIEast Boundary (longitude)\fP
この境界を指定すると、画像は境界で区切られ範囲の外側は表示しません。緯度と経度は全て入れましょう。西経は負の数字、東経は正の数字を入れます。"-180.0"から "180.0"の範囲です。
.TP 20
          \fIScale (norm 1.0) or output width\fP
地図投影の大きさを指定します。初めは"1.0"です。"0.5"は縦横が半分の大きさ、"2.0"は2倍の大きさの画像になります。最良な大きさはありません。でも、拡大率や縮小率を変えた画像が低品質になるとこがあります。"50"以上は、この幅の画像を作成するために適切な大きさを選びます。"2.0"(または50未満)を越える数字は、有効では無いことがあります。
.TP 10
\fISampling Frequency...\fP
この機能は、
[Enable expert mode]
を使うと表示されます([Options]中
[GUI Options]
にあります)。
サンプリング割合は、[Image]にある
[Slant Correction]
を使い非常に簡単に、正確に指定できます。
または、ここにサンプル割合の入力指定ができます。サンプル割合は、例えば次の5つ種類の毎秒サンプルに替えてみましょう。貴方が毎秒11025を使っているならば、11020,11030,11015,11035,11010,11040等に替えてみましょう。PLLが有効になり画像を直線状にするように調節して下さい。通常はこの調整を一度だけ行って下さい。0.0の指定は、
[Default Sampling Frequency]
を使います。
.TP 10
\fIImage and Movie Options...\fP
画像とAVIに関する多様な機能があります。
.TP 20
          \fIDefault Image Format\fP
普段使う画像形式を、JPEG、PNG、BMP、PBM(PGM/PPM/PNM)、AVIの内から一つを選んで指定して下さい。これは画像の自動保存に使われます。
[File]にある
[Save Image as...]
で保存すると、WXtoImgは保存形式を決めるのに拡張子を使います(.png、.bmp、.pbm、.pgm、.ppm、.pnm、.jpg、.jpeg、.aviを小文字あるいは大文字)。
拡張子が指定されないか不明ならば、ここに指定された画像形式になります。
.TP 20
          \fIDefault for Anaglyphs\fP
疑似立体表示に使う画像形式をJPEG、PNG、BMP、PBM(PGM/PPM/PNM)の内から一つを選んで下さい。これは画像の自動保存に使われます。JPEGによる色の変質が、立体画像に影響します。ですから、損失がない画像形式(PNG,BMP,PBM)が、疑似立体画像(Anaglyphs)に良いでしょう。
.TP 20
          \fIDefault for Composites\fP
複合画像に使う画像形式をJPEG、PNG、BMP、PBM(PGM/PPM/PNM)の内から一つを選んで下さい。これは画像の自動保存に使われます。複合画像の重ね合わせは、JPEG形式による画質の損失をさらに重ねるおそれがあるので、複合画像(Composites)は、損失が無い画像形式(PNG、BMPあるいはPPM)で最も保存されます。
.TP 20
          \fIJPEG Quality\fP
JPEGの画質を指定します。初めは65です。有効な範囲は0から100です。"Image Output Formats"の項目も見て下さい。
.TP 20
          \fIHVC Palette\fP
HVC増強用調色を選びます。PNG、BMPとPPM形式で使われます。技術的な詳細に関しては、WXtoImgコマンドラインマニュアルの-Pオプションを参照して下さい。この項目を空白にすると、あらかじめ用意したHVC調色を使います。
.TP 20
          \fISea Surface Temp Palette\fP
海表面温度用の調色を使い、太陽光海表面温度増強を行います。BMPとPPM形式の両方が扱えます。技術的な詳細に関しては、WXtoImgコマンドラインマニュアルの-Pオプションを参照して下さい。空欄の場合は、標準な海表面温度調色を使用します。
.TP 20
          \fIMSA Sea to Land\fP
多重波長解析(MSA)の海面から地表にかけての修正です。初めは"50"です。多重波長解析増強を使い、地表が青色になるならば数を減らし、水表面が緑色になるならば数を増やしましょう。有効な範囲は"0"から"100"です。この機能は、
[Enable expert mode]
([Options]中
[GUI Options]
にあります)を使うと表示され、初めは"50"です。
.TP 20
          \fIMSA Land to Cloud\fP
多重波長解析(MSA)の地表から雲にかけての修正です。初めは"50"です。多重波長解析増強を使い、雲が緑色になるならば数を減らし、地表が灰色か白色になるならば数を増やしましょう。有効な範囲は0から100です。この機能は、
[Enable expert mode]
([Options]中
[GUI Options]
にあります)を使うと表示され、初めは"50"です
.TP 20
          \fIAVI Codec\fP
AVI動画に使う圧縮方法です。MJPG、JPEGとRGBがあります。
MJPG(モーションJPEG)は優れた圧縮に使えます。JPEGは低圧縮です(標準化はされないでしょう)。RGBは圧縮を全く行いません。
BeOSでは、JPEGをお勧めします(使えるMJPGデコーダが無い場合)。
他の全てのオペレーティングシステム(OS)では、MJPGをお勧めします(MS-Windows用のMJPGデコーダは、DirectXで使えます)。
JPGQとlJPGSコーデックは、互換性を保ちつつ、今後も利用されるでしょう。
.TP 20
          \fIAVI Transparency\fP
前のコマにある画素を次のコマが使わないように、AVI画像の背景を透明にします。
[AVI Quality]
の数を高めるか、
"RGB AVI Codec"
を使うと良い結果になるでしょう。この機能は、初めは使われています。
.TP 20
          \fIAVI Quality\fP
AVI動画の質を指定します。初めは"20"です。有効な範囲は"0"から"100"です。[Image Output Formats]を参照して下さい。
.TP 20
          \fIAVI Max Frames\fP
動画の最大コマ数です。新しい画像を加えたときに、この最大数を超えたならば、最初のコマが消されます。
.TP 20
          \fIAVI Frame Rate\fP
動画の毎秒コマ数です。通常は0.2(1コマ5秒)から8.0(毎秒8コマ)の範囲が使えます。初めは"1.0"です。
.TP 20
          \fIAVI Scale\fP
画像表示を縮小します。"0.0"からと"1.0"の範囲が使えます。初めは"0.5"です。
.TP 10
\fIFile Names and Locations...\fP
各ファイルを保存する場所を指定します。
.TP 20
           \fIAudio file naming\fP
音声ファイル名は録音時刻を用います。他の時間形式に変更もできます。この指定は、WXtoImgが行う、音声ファイルが録音された時刻の判断に影響するので注意しましょう。[Other]を選ぶと、WXtoImgはファイル名から録音時刻を決定しません。また、音声ファイルは[MMDDHHMMの世界標準時]として記録されるでしょう。
.TP 20
          \fIFilename Template\fP
普段使うファイル名と受信録音中のファイル名を指定します。空白のままなら
ば書き入れた名前と記録時間(%T:月日時分)の形式にします。詳細は、後述の
"画像名について(Filename Template)"
を参照して下さい。
.TP 20
          \fIUse for audio recordings/maps too\fP
これを選ぶと、受信録音と全ての地表図は、解析後に保存名形式と一致させるために改名されます。受信録音のみで解析をしないならば、受信録音と地表図は改名されません。
.TP 20
          \fIAudio File Location\fP
受信録音を保存するディレクトリやフォルダを指定します。解析するファイルを選ぶときは、このディレクトリを開けます。
.TP 20
          \fIRaw Image Location\fP
受信録音をするときに、PNGとPBM(PGM)形式を保存するディレクトリやフォルダを指定します。raw画像を選んだり保存するときも、このディレクトリにします。
.TP 20
          \fISave Image Location\fP
解析や増強処理された画像を、[File]の
[Save Imageas...]
で保存するディレクトリやフォルダを指定します。
.TP 20
          \fIMap File Location\fP
録音時と解析時に地表図を保存するディレクトリやフォルダを指定します。
.TP 20
          \fIThumbnail Location\fP
縮小表示を保存するディレクトリやフォルダを指定します。
.TP 10
\fIGUI Options...\fP
画面操作(GUI)に関する指定をします。
.TP 20
          \fITemperature units\fP
C(摂氏)、F(華氏)、K(絶対温度)のどれかを温度表示に選んで下さい。初めは、摂氏表示です。
.TP 20
          \fIDistance units\fP
Km(キロメートル),nm(海里),mi(マイル)のどれかを距離表示に選んで下さい。初めは、Km表示になっています。
.TP 20
          \fIHelp Language\fP
EN(英語)、ES(スペイン語)、DE(ドイツ語)、JA(日本語)、PL(ポーランド語)をHelp表示に選んで下さい。この他の言葉のほとんどは未だ表示できません。貴方が各国にある言語のどれかに翻訳できるならば、http://www.wxtoimg.com/email.htmlまでお知らせ下さい。
.TP 20
          \fIHelp Font Size\fP
Help表示をする文字の大きさを替えます。"+0"が初めの指定です。負の数字は文字を小さく、正の数字は文字を大きく表示します。
.TP 20
          \fIDate/time format\fP
WXtoImgが表示する日付と時間の形式を変更できます。Upgrad版が表示できます。
.TP 20
          \fIShow time as UTC\fP
選ぶと世界標準時(UTC)を、印を外すと現地時間を表示します。(Upgrade版のみ)
.TP 20
          \fIEnable map and projection support\fP
初めは、選ばれています。印を外すと画像表示には、地表図表示や地図投影法、MSA増強(多重波長解析)、MCIR増強、太陽光のむら修正を行わないので、CPUが遅い機種では画像表示が早まります。
MSA増強とMCIR増強や他のWXtoImg機能は、コンピュータに負担がかかるので、WXtoImgの各機能が無理なく使える時に、この機能を使うように強くお勧めします。この機能は、
[Enable expert mode]
を使うと表示されます([Options]中
[GUI Options]
にあります)。
.TP 20
          \fIFlip Meteor series 3 images\fP
Meteor3の画像は、保存しません。地表図および投影法が無効でも、Meteor3の全ての画像が上下逆さまになってしまうようならば、これが役立つでしょう。この機能は、初めには使われません。また、この機能は
[Enable expert mode]
([Options]中
[GUI Options]
にあります)を使うと表示されますが、Meteor3-21が現在は送信をしていないので、ほとんど役に立ちません。
.TP 20
          \fIUse private colormap\fP
ディスプレイが256色(8ビット)ならば、新しい調色(ColourMap)を取り込み、WXtoImgが使える256色を用意します。(他の全てアプリケーションとOSに共有します)この指定は、HighColor(15・16ビット)やTrueColor(24・32ビット)には使いません。この機能は、
[Enable expert mode]
を使うと表示されます([Options]中
[GUI Options]
にあります)。
.TP 20
          \fITear off menus\fP
次回にWXtoImgを使うときに、各項目の一番上に表示される破線を押しましょう。各項目が別枠になり画面上の好きな所に置けます。これは、増強などの変更をしやすくなります。Upgrade版のLinuxとMS-Windowsで使えます。
.TP 20
          \fIAutomatically enter record mode\fP
[File]にある[Record]中の[Record]ボタンを押したのと同じ様に、WXtoImgが自動に受信録音待機になります。ATP衛星では、次の衛星通過数分前、又は解析が完全に終わると受信録音待機になります。これは、WXtoImgが自動に働き始め、録音と解析を自動化するのに有効です。Upgrade版で使えます。
.TP 20
          \fIDisable sat position during record\fP
衛星通過を録音中に、衛星の位置計算(高さと方位角)と表示をしません。処理が遅いコンピュータに役立ちます。
.TP 20
          \fIAutomatically update Keplers\fP
24時間毎にインターネットへ接続し、軌道要素を取り入れます。常にインターネットへ接続しているか、自動接続ができるならばこの機能を使えます。受信録音をしているUpgrade版のみ使えます。
.TP 20
          \fIAuto-save options on exit\fP
WXtoImgを終える時に、設定の変更が保存されます。
[Save Options]
と同様です。初めは選ばれています。
.TP 20
          \fIMaximum number of thumbnails\fP
各タブに表示される縮小表示の最大数を指定します。最新のものが表示されます。
.TP 20
          \fIEnable Expert Mode\fP
あまり使われない機能を使えるようになります。印を付けたならば、
[Save Options]
を押して、一度WXtoImgを終えて下さい。
.TP 10
\fISave Options\fP
[Options]全てを保存します。ただし、[Interpolate]、[NoiseFilter]、[ShowAll]、[Resync]、
[Disable PLL]
の指定は保存しません。画面表示位置とその大きさもや記録方法、画像と動画の指定も保存します。もし保存をしないと、次にWXtoImgを使う時には変更が使えません。(ただし、[GUI Options]にある
[Auto-save options on exit]
を選ぶならば保存されます)
.PP
.SH Projection (地図投影法)
ここでは、APT衛星画像の表示に使われる地図投影法を指定します。変更しないならば、[Normal]で表示されます。
.TP 10
\fINormal\fP
衛星が送るそのままを、変換しない投影法で表示します。
.TP 10
\fIMercator\fP
メルカトル図法
航路線(一定方向の線)は、直線に見えます。この円筒図法は赤道付近から両極に近づくにつれて、面積は歪みます。
.TP 10
\fIEquidistant Cylindrical\fP
正距円筒図法
経度線と緯度線のます目が正方形になります。標準緯線を0度とすると
"Plate Carree図法"
と呼ばれます。両極付近で相当な歪みがあります。
.TP 10
\fIEqual-Area Cylindrical\fP
正積円筒図法
同緯度では、どの経度でも同面積を表示します。両極付近で相当な歪みがあります。
.TP 10
\fIEckert IV\fP
エケルト図法(第4図法)
半円状の子午線を持つ正積図法です。世界地図用に使われます。
.TP 10
\fIEckert VI\fP
エケルト図法(第6図法)
サイン曲線の子午線を持つ正積図法です。世界地図用に使われます。
.TP 10
\fIMollweide\fP
モルワイデ図法
一般には世界地図用に使われる正積図法投射法です。
.TP 10
\fIMiller\fP
ミラー図法
メルカトル図法より歪みが少ない疑似法円筒図法ですが、航路線は直線になりません。
.TP 10
\fIPolar Lambert Equal-Area\fP
ランベルト正積方位図法
極中心のランベルト正積方位の投影法です。方位図法類の極平射図法ですが、面積は正しく表示できます。
.TP 10
\fIPolar Stereographic\fP
極平射図法
経度線が極に集中する方位図法です。
.TP 10
\fIPolar Azimuthal Equidistant\fP
極正距方位図法
経度線が極に集中する正距図法です。
.TP 10
\fIOrthographic\fP
正射図法
視点が無限遠からの投射図法です。
.PP
.SH Image (画像操作)
解析後に画像を変える機能です。
.TP 10
\fISlant Correction...\fP
サンプリング割合を指定する為に、マウスを使って縦線に沿って線を引きます。詳細は、[Help]にある
[Required Calibration...]
を参照して下さい。
.TP 10
\fIMove Map Overlay...\fP
地表図を移動します。マウスボタンを押したままポインタを動かし、地表図とそれに対応する衛星画像の部分へ線を引き合わせます。
.TP 10
\fIColour Negative\fP
反転色調画像を表示します。グレースケール(grayscale)の黒が白く、白が黒になります。
.TP 10
\fIWarmer Colours\fP
画像中の遠赤外線部分を暖色へ変換します。結果は微妙なので、何度か繰り返す必要があるでしょう。
.TP 10
\fIColder Colours\fP
画像中の遠紫外線部分を冷色へ変換します。結果は微妙なので、何度か繰り返す必要があるでしょう。
.TP 10
\fIConvert to Grayscale\fP
画像を白黒多諧調に変換します。
.TP 10
\fIHistogram Equalise Image\fP
ヒストグラム均一化をします。8ビット画像には、増強後にこのヒストグラム均一化を行うと低画質になるので注意して下さい。しかし、拡大画像等には効果があります。(この機能は16ビットで効果があります)
.TP 10
\fIIncrease Contrast\fP
画像の明暗差を増します。明暗差が鮮明になるように複数回使って下さい。
.TP 10
\fIFlip Image\fP
画像を180度回転させます。
.TP 10
\fIWhite Background...\fP
幾何学的に変換された画像(つまり、地図投影法が"Normal"以外で使われます)の背景を黒から白に変えます。この機能は[File]にある
[View Image]
から表示したJPEG画像には使えません。自動的に保存された画像の背景を変更する為には、[File]にある[Record]中の
[Image Settings]
で
[White background on projections]
を使って下さい。
.TP 10
\fIShift Image...\fP
表示された画像上をマウスでクリックすると、その位置が画像の左端になります。
.TP 10
\fICrop Image...\fP
赤線で表示される四角の枠をクリックしたまま移動させ、切り取る画像の範囲を選びます。その後、枠内を押し画像を表示させます。枠外を押すとこの操作は無効になります。
.TP 10
\fIRotate Image...\fP
画像を回転します。左から右へ線をマウスで引いて下さい。この線が回転後の画像で水平になります。
.TP 10
\fIResize Image...\fP
一覧から、再表示する大きさ(元に対する割合)を選びます。
これは画像の大きさを単に縮小します。画像は、極小表示の為に数回縮小することができます。
.TP 10
\fIMagnify Area...\fP
一覧からは拡大率と、拡大する範囲をマウス操作で決めてから、その範囲内(赤線内)を押すと拡大表示します。範囲外を押すとこの操作は取り消されます。
.TP 10
\fIView Enhancement Curve\fP
[Enhancements]で選び使われている増強曲線と調色を表示します。増強がヒストグラム均一化増強ならば、そのヒストグラムが表示されます。
.TP 10
\fIUndo All (Decode)\fP
増強の種類を変更したり、変更分の画像を作るために再解析をします。
.PP
.SH 画像名について (Filename Template)
WXtoImgが作る画像名の形式を指定するのに使います。[Options]にある
[File Names and Locations..]
を見て下さい。
[Filename Template]
が空白のままならば、元のままの名前になります。
.PP
下記にあるように、名前の変更ができます。文字は、全て小文字になります。
.PP
例えば[Filename Template]に次を記入すると:
.nf
    %s-%T-%e
.fi
.PP
ファイル名は次の様になります:
.nf
    meteor3-06081123-norm.jpg
    noaa-17-06082348-msa.bmp
    noaa-06082352-mcir-precip.png
    noaa-06082350-raw.png
    met7-06082603-norm.png
.fi
.PP
年月日の指定は次になります:
.nf
    %Y/%m/%d/%s-%e
    %Y\\%m\\%d\\%s-%e
    %Y:%m:%d:%s-%e
.fi
.PP
Linux、*NIXやMS-Windows、DOS、MacOSそれぞれに同じ表記をします。
.PP
.TP 10
\fB%@\fP
世界標準時ではなく、現地時刻を表示します。"%@"の後に省略した時刻帯を入れて下さい。(例えば、日本は"JST")
.TP 10
\fB%s\fP
小文字の衛星名にします。(8文字以内。例えばmet7, noaa-14, meteor3など)
.TP 10
\fB%N\fP
大・小文字と文字間のある衛星名にします。(例えばMET7, NOAA 17, Meteor3-5)
.TP 10
\fB%g\fP
小文字の衛星の種類名にします。(例えば、met, noaa, meteor3)
.TP 10
\fB%D\fP
飛行方向にします。(例えば、northbound, southbound)
.TP 10
\fB%p\fP
一文字の飛行方向にします。(例えば、北行はN, 南行はS)
.TP 10
\fB%E\fP
最高角度にします。(例えば、0から90)
.TP 10
\fB%^\fP
最高角度時の方位角にします。(例えば、0から360)
.TP 10
\fB%z\fP
一文字の最高角度時の方位にします。(例えば、E,W)
.TP 10
\fB%:\fP
衛星の最大仰角になる方位を表示するために、\fBeast\fP もしくは \fBwest\fP になります。
.TP 10
\fB%f\fP
元の音声名にします。ただし、ディレクトリ名と拡張子は省きます。(例えば、"/tmp/03042215.wav"は"03042215")
.TP 10
\fB%F\fP
atpあるいはwefaxにします。
.TP 10
\fB%C\fP
3文字でWEFAXのスペクトルバンド名、あるいはNOAA,APTチャンネル名にします。例えば、WEFAXはvis,ir,nirなどです。NOAA,APTは2-4,3-4です。不明ならば変更しません。
.TP 10
\fB%e\fP
増強名にします(例えばza,hvc)rawは"raw"、pristineは"pris"、normalは"norm"になります。[histeq]や[norm]増強でA、Bどちらかのチャンネルを使う場合は、チャンネル名が入ります。(例えば、histeqb,contrasta,norma)
.TP 10
\fB%l\fP
セクタ名にします。これは、WEFAXディジタルヘッダの4文字以内のセクタ情報です。利用できないならば(APTも)変更はしません。
.TP 10
\fB%8,9,10,11%\fP
第9,第10,第11,第12番目のWEFAXディジタルヘッダ番号にします。(0は始めに付けるので、1から付けます)0から49が、ディジタルヘッダ中で50文字に相当する数です。0で始まる数字は、コンマ(,)によって分れます。"%"は一連の番号を終えます。スペース文字は変更をしません。(ファイル名はスペース文字を含みません)
.TP 10
\fB%r\fP
送信周波数(MHz)にします。(例えば、137.50)
.TP 10
\fB%k\fP
年月日(YYMMDD)の日付にします。WEFAXではディジタルヘッダに含まれる日付です。APTでは現在の世界標準時を使います。(%y%m%dと同様です)
.TP 10
\fB%K\fP
%kと同じですが、DDMMYY(日月年)にします。(%d%m%yと同じです)
.TP 10
\fB%L\fP
%kと同じですが、MMDDYY(月日年)にします。(%m%d%yと同じです)
.TP 10
\fB%d\fP
日の2数字にします。(01から31)
.TP 10
\fB%m\fP
月の2数字にします。(01から12)
.TP 10
\fB%y\fP
世紀を省いた年にします。(例えば03)
.TP 10
\fB%Y\fP
世紀がある年にします。(例えば2004)
.TP 10
\fB%T\fP
月日時分(MMDDHHMM)にします。WEFAXではディジタルヘッダに含まれる時刻です。APTでは現在の世界標準時になります。(%m%d%H%Mと同様です)
.TP 10
\fB%t\fP
時分(HHMM)にします。WEFAXではディジタルヘッダ含まれる時刻です。APTでは現在の世界標準時になります。(%H%Mと同様です)
.TP 10
\fB%H\fP
時を24時間制にします。(00-23)
.TP 10
\fB%I\fP
時を12時間制にします。(00-12)
.TP 10
\fB%P\fP
AMかPM(午前/午後)にします。
.TP 10
\fB%M\fP
分にします。(00-59)
.TP 10
\fB%Z\fP
省略した時刻帯にします。(JSTなど)
.TP 10
\fB%%\fP
%を表記します。
.PP
.TP 10
訳者: Filename Templateを箇条書きにしました。
.br
%@(Local Time Zone) 現地時間
.br
%s  小文字衛星
.br
%N  大・小文字衛星
.br
%g  小文字種類名
.br
%D  飛行方向
.br
%p  略飛行方向
.br
%E  最高高度
.br
%^  方角
.br
%z  略方角
.br
%f  Audio名
.br
%F  atp,wefax
.br
%C  WEFAXはスペクトルバンド名。APTはチャンネル名
.br
%e  増強処理
.br
%l  セクター名(WEFAXのみ)
.br
%n  シーケンス番号
.br
%8,9,10,11%  第9、第10、第11、第12番目のWEFAXディジタル・ヘッダ名
.br
%r  送信周波数
.br
%k  年月日
.br
%K  日月年
.br
%L  月日年
.br
%d  日(01-31)
.br
%m  月(01-12)
.br
%y  2桁年(03)
.br
%Y  4桁年(2004)
.br
%T  月日時分
.br
%t  時分
.br
%H  24時間制
.br
%I  12時間制
.br
%P  AM/PM
.br
%M  分
.br
%Z  時刻帯
.br
%%  %
.PP
.SH 画像形式 (Image Output Formats)
WXtoImgが扱う画像は \fIJPEG\fP, \fIPNG\fP, \fIBMP\fP, \fIPBM\fP(PGM/PPM/PNM), \fIAVI\fP形式です。
.PP
[Options]の[Image and Movie Options]を見て下さい。
.PP
JPEG(.jpg)、PNG(.png)、BMP(.bmp)、PNM(.pnm)、AVI(.avi)の各形式は拡張子によって決まります。貴方が拡張子を使わないか、拡張子が使用できる出力形式ではないならば、[Options]にある
[Image and Movie Options...]
で指定した形式になります。
.PP
JPEGは圧縮形式で損失があるかもしれません。[JPEG quality]
([Options]の
[Image and Movie Options]にあります)
は、保存さる詳細部分の量と圧縮率を操作することができます。
(これは[Options]の
[Imageand Movie Options]
にあります)
"0"から"100"の範囲で変えられ、有用な範囲は"30"から"95"です。"30"は高圧縮の画像(かなり多くの詳細な部分は省かれます)になり、"95"は低圧縮で良質な画像を作ります。JPEGは16ビット白黒多諧調画像を扱えません。JPEG画像は文字を含むことができます。
.PP
PNGは圧縮損失がない画像形式です。損失がない好ましい圧縮形式です。PNGは16ビットの白黒多諧調画像、文字とガンマを扱えます。
.PP
BMPはコンピュータに広く使用される画像形式です。WXtoImgが作ったBMP画像は圧縮されません。BMPは16ビット白黒多諧調画像と文字を扱えません。
.PP
PBMは未圧縮の画像形式で、*NIXでの処理と画面表示に適しています。PBMは、PPM(有色)、PGM(白黒多諧調)とPNM(その他)と呼ばれます。これらは16ビットの白黒多諧調画像と文字を扱えます。
.PP
AVIは豊かな表現ができます。AVIは、未圧縮RGBとJPEG圧縮をするJPEGと略式JPEG圧縮を使うMJPG(あるいはMotionJPEG)など異なるタイプの圧縮が扱えます。AVIで使われる圧縮の種類は、
[AVI Codec]
の設定要素で扱われます。
.PP
JPEGとMJPGの画像品質がAVI動画の品質を左右します。([Options]の
[Image and Movie Options]
にあります)
AVIは、良質な圧縮の為に低い画質を使います。これは、動画の滑らかな動きには低品質画像が適しているからです。
貴方がAVI動画を作る時に、同じ名前の動画があるならば、新しい画像が動画の後に加わります。AVI動画がなければ、新しい一連のコマのみで作られます。
AVI動画が既に最大コマ数だったり、動画が多量な一続きのコマを含んでいるならば、コマの総数が最大数内になるように最初のコマ部分が削除され、その後に新しい画像が加えられます。
.PP
.SH 音量調整について (Volume Control)
信号を録音する時に、音量の高低に片寄りが無いことが大切です。音量が高すぎると、画像の明るい領域の細かい部分が失われます。音量が低すぎれば、画像の細かい部分が失われます。
.PP
解析中の音量表示が、約50.0から75.0の範囲になるように音量を調節しましょう。音量表示が例えば93.2の様に高いならば、音量を下げましょう。24.7の様に低い表示ならば、音量を下げましょう。
.PP
受信が始まると音量が表示されます。衛星の通過中に受信機の音量は、簡単に調整できます。衛星ごとに音量を変えることは、昼夜を問わずお勧めしません。音量調整を一度行ったならば、その状態にしておきましょう。
.PP
8ビット音声ファイルを使うならば、音量を85.0から92.0の範囲になるように、音量をゆっくりと上げましょう。残念なことに、各衛星ごとに異なる音量を決める必要があります。8ビットでは、画像増強を行ってもその画像は16ビットの画像ほど良くなりません。
.PP
音量が高すぎると、WXtoImgは警告を表示するでしょう。
.PP
.SH 機器の案内 (Equipment Required)
APT信号にこのプログラムを使うには、137MHzから138MHz帯(137.30,137.40,137.50,137.62,137.80,137.85MHz)のFM信号が扱える受信機が必要です。WXtoImgは、感度と中間周波数(IF)帯域幅(約50kHz)を正確に受信できる気象衛星受信機に合うように設計されています。
.PP
広域受信機と一般な無線機が使えます。でも、それらのほとんどが狭いIF帯域幅(15kHz程度)なので、画像の白色部分(0から255段階の約128段階)の多くが消されます。衛星が頭上を通過する時に、狭いIF帯域幅と組み合ったドップラー効果が、貧弱な信号の原因となり、さらに多くの雑音を引き起こすでしょう。それでも、WXtoImgのUpgrade版は、RS-232接続を持つ無線機には、ドップラー補正の為に周波数調節ができます。
.PP
また、数種類の受信機は、30kHzもしくは50kHzのIFフィルタを持っています。(30kHzは、WXtoImg,Upgrade版で周波数調節されるならば使えます)また、IF帯域幅を増やす機能を持つ広域受信機がいくつか在ります。
.PP
アンテナと受信機の間に置くアンプは、貧弱な信号の感度を増加できます。しかしこれらを用いてもは、気象衛星専用受信機と同様の画質にはならないでしょう。
.PP
Upgrad版のWXtoImgは特別な処理ができるので、狭い帯域幅の受信機を使っても正しい色増強が行えます。Upgrad版は、
[Contrast enhance (NOAA ch B only)]
を使う画像では、適正な画像を得るためにかなりの利点があります。
.PP
貴方の受信機がどのような種類でも、特別なアンテナが必要になります。そのアンテナは自作できます。お勧めのQFHアンテナの設計と自作例がウェブサイトにあります。ターンスタイルやダイポールアンテナも良いですよ。
.PP
もちろん、サウンドカードの"ラインイン"と、受信機の"スピーカアウト"を繋げるケーブルが必要ですね。
.PP
極軌道の気象衛星が何時に上空を通過するか知るために、衛星軌道ソフトが必要だと貴方は思うでしょう。でも、WXtoImgは受信録音待機中に次の衛星通過時刻を表示します。
.PP
静止衛星からのWEFAX受信には手頃な椀型アンテナと、1600MHz帯信号を137MHz帯にする変換器を使う方法が最も一般的です。そうすれば、137MHz帯受信機を静止衛星に使うことができます。
.PP
次の"参照と案内(References and more Information)"もご覧下さい。
.PP
.SH 参照と案内 (References and more Information)
ポール・ヘインズは、QFHアンテナを案内しています。
.nf
    http://homepage.ntlworld.com/phqfh1/qfh_diy_guide.htm
.fi
.PP
WXtoImgについての情報やFAQは、次のURLを参照して下さい。
.nf
    http://www.wxtoimg.com/
.fi
.PP
.SH 動作不良 (Known Bugs)
録音が無い間の再同期(resync)機能は、不正確に働くことがありあます。
.PP
Okean衛星の自動認識は、通常働きません。Okean衛星からの録音を解析する前に[Satellite]にある[Okean]を選んで下さい。
.PP
Okean衛星のトリガは、ドップラー効果のために斜めの画像では使えません。Okean衛星とMeteosat衛星では、サウンドカードと一致するサンプル割合を正確に指定する必要があります。
.PP
.SH 使用条件 (Terms and Conditions)
このプログラム(wxtoimg、xwxtoimg、wxrec、wxbatchを含む)は、不具合を含まないとは限りません。このWXtoImgをインストール前に、システムの保存をお勧めします。"root"や管理者権限や"admin"あるいはシステム特権でこのWXtoImgを使うことは、避けましょう。なぜならば、アナログ信号等の複雑な処理の為に、このプログラムの全てが正確に動くとは限らないからです。
.PP
WXtoImgプログラムと関係する文書は、元のまま貴方の手元に届きます。
"Central North Publishing Limited"
は、無制限の保証の全てを放棄し、WXtoImgプログラムの使用に起因する直接、間接、付帯的、特別、典型な、あるいは間接な損害の可能性を知らされたとしても、直接は責任を負いません。
.PP
WXtoImgプログラムと関連文書は、生命、健康、安全性あるいは財産が危険にひんしている際に使われるようには、意図されてません。
.PP
Freeware版のWXtoImgは、個人で非商業的な目的にどうぞ無料で使って下さい。追加機能はUpgradeをされると利用できます。
.PP
商用に使用する企業や個人は、Professional版へ変更をする"Upgrade key"をご購入して下さい。"Upgrade key"は次から得られます。
.nf
    Central North Publishing Limited
    P.O. Box 99597
    Newmarket
    Auckland
    New Zealand
    Email: http://www.wxtoimg.com/email.html
    http://www.wxtoimg.com/reg/
.fi
.PP
WXtoImgプログラムと文書は、個人使用のために、非商業的な方式で元パッケージを再配布できます。他の方法の再配布は、許されません。
.PP
"Central North Publishing Limited" は、再配送を止める権利を持ちます。
.PP
"Upgrade keys"
は単一のコンピュータでお使いになり、他では使わないで下さい。
.PP
著作権は、2001-2013年付でCentral North Publishing Limited 株式会社に全て帰属します。
.PP
The WXtoImg programs are Copyright (c) 2001-2010 Central North Publishing Limited. All rights reserved.
.SH 関係者 (Credits)
Andreas Rehberg, Gerd Berg (DK1RR), John Boudreau, Adrian Chamberlain, Ari Ervaskivi, Andy Eskelson, Jakub Gorzynski (SQ2WB), Les Hamilton, Nakato Mikiya, Paul Hayes, Paul Holder, Pauli Nunez (EA3BLQ), Andre Phillips, Steven Ross, Jeremy Royle,
Hartmut Schaksmeier
及びWXtoImgの初期版を評価して頂いた多くの方々に感謝します。
.PP
アメリカ海洋大気庁(NOAA)は、ウェブサイト及び出版物で豊富な情報を提供し、WXtoImgの中で使われるほとんどの増強曲線を開発しました。
.SH 掲示 (Notices)
Copyright (c) 2001-2004 Central North Publishing Limited. All rights reserved. Translated by Nakato Mikiya.
.br
著作権は、2001-2010年付で"Central North Publishing Limited" に全て帰属します。
.PP
ZA, MB, MD, BD, CC, EC, HE, HF, JF, JJ, LC, TA, WV, NO の各増強曲線は、アメリカ海洋大気庁(NOAA)から提供されました。
.PP
JPEGは"Independent JPEG Group"により支援されています。
.PP
画像中の文字は"FreeType Team"に基づきます。
.PP
.PP
この文書の日本語訳は、中藤 幹也が行いました。
何かございましたら、次のURLをご覧下さい。
.nf
    http://globe.dyndns.org/
.fi
