.\" -*- nroff -*-
.\" Copyright (c) 2001-2004 Central North Publishing Limited.
.\" All rights reserved.
.\"
.\" Polskie t³umaczenie: Jakub SQ2WB 
.\"
.TH WXTOIMG UPGRADE  "version 2.7.3"
.SH Upgrade
.B Jak rozszerzyæ funkcjonalno¶æ programu?
.br
Wykorzystuj±c przegl±darkê internetow± przejd¼ pod adres:
.nf
    http://www.wxtoimg.com/reg/
.fi
.PP
Nastêpnie postêpuj zgodnie ze wskazówkami ze strony. Za nisk± op³atê zostanie do Ciebie wys³any osobisty klucz rejestracyjny, który uaktywni dodatkowe funkcje.
.PP
.B Dlaczego powinienem rozszerzyæ funkcje?
.br
Kupienie wersji rozszerzonej umo¿liwia dalsze rozwijanie programu. Dodatkowo otrzymasz dostêp do wielu dodatkowych funkcji.
.PP
Istniej± dwie edycje rozszerzenia - Standard oraz Professional
.PP
.B Jakie dodatkowe mo¿liwo¶ci daje mi rozszerzona edycja programu?
.br
Przekszta³cenie Anaglyph 3-D. Umo¿liwia przedstawienie chmur w zachwycaj±cy, trójwymiarowy sposób. Stworzone obrazy trzeba ogl±daæ poprzez czerwono-niebieskie okulary 3D.
.PP
Udostêpnia przekszta³cenie z nak³adk± z szacunkowymi opadami.
.PP
Znacznie poprawia jako¶æ obrazu uzyskiwanego z odbiorników o w±skim filtrze (np. skanerów, odbiorników komunikacyjnych).
.PP
Strony internetowe mog± byæ ca³kowicie personalizowane.
.PP
Udostêpnia wiele nowych projekcji (przekszta³ceñ geograficznych) w³±czaj±c w to projekcje Mercator wraz z opcjami transformacji obrazów z satelitów APT (punktem odniesienia, d³ugo¶ci± geograficzn±, skal± oraz granicami).
.PP
Umo¿liwia stworzenie filmów animowanych z kilku obrazów pochodz±cych z satelitów oko³obiegunowych (sta³y l±d, poruszaj±ce siê chmury).
.PP
Mog± zostaæ stworzone kompozycje wielu obrazów z satelitów oko³obiegunowych obrazuj±ce bardzo du¿e obszary.
.PP
Umo¿liwia funkcje obrotu wraz z przesuwaniem palety kolorów oraz konwersj± odcieni szaro¶ci.
.PP
Umo¿liwia automatyczne pobieranie aktualnej pozycji geograficznej z GPS (NMEA).
.PP
Umo¿liwia wy¶wietlanie czasu lokalnego zamiast UTC.
.PP
Pokazuje szeroko¶æ i d³ugo¶æ geograficzn± miejsca, które wska¿emy kursorem wraz z informacj± o odleg³o¶ci i kierunku od naszej stacji.
.PP
Informacje tekstowe mog± byæ wy¶wietlane na zdjêciach w wybranym kroju oraz kolorze czcionki. Ca³o¶æ mo¿e byæ zautomatyzowana, dziêki czemu mo¿emy umie¶ciæ informacje o satelicie, czasie oraz wiele innych zwi±zanych z przelotem oraz zdjêciem szczegó³ów.
.PP
Menu programu mo¿e zostaæ "wyrwane". Umo¿liwia to ³atwiejszy wybór przekszta³ceñ oraz opcji (funkcja nie jest dostêpna dla MacOS)
.PP
Umo¿liwia kontrolê nad urz±dzeniami: FT-847, PCR100/PCR1000, R2FX, SAN 200, WRX-137, AOR, Uniden, Bearcat, ICOM, oraz Kenwood. Mo¿e tak¿e wspó³pracowaæ z dowolnym programem kontroluj±cym dostarczonym przez u¿ytkownika.
.PP
Pozwala na skonfigurowanie programu do automatycznego przej¶cia w tryb nagrywania oraz dekodowania przy starcie, dziêki czemu mo¿liwe jest ca³kowicie zautomatyzowane rejestrowanie przelotów.
.PP
Dodatkowo przysz³e prace nad programem bêd± siê skupia³y na funkcjach dostêpnych tylko dla u¿ytkowników edycji Standard.
.PP
Edycje Standard oraz bezp³atna nie mog± zostaæ wykorzystane w celach komercyjnych.
.PP
.B Jakie dodatkowe funkcje zostan± udostêpnione w edycji Professional?
.br
Edycja Professional udostêpnia wszystkie funkcje edycji Standard, wraz z:
.PP
du¿ym wyborem algorytmów próbkuj±cych (dla przekszta³ceñ geograficznych)
.PP
dodatkowymi opcjami filtrów przeciwzak³óceniowych
.PP
dodatkowymi opcjami kontrastu
.PP
Edycja Professional mo¿e byæ wykorzystywana w celach komercyjnych.
.PP
.B Dziêkuje z góry za rozszerzenie funkcjonalno¶ci na stronie
.nf
    http://www.wxtoimg.com/reg/
.fi
.PP
.SH Prawa autorskie
Copyright (c) 2001-2004 Central North Publishing Limited.  All rights reserved.
.PP
Polskie t³umaczenie: Jakub  SQ2WB
